#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

AVATAR_DIR=/app/ghostwriter/media/user_avatars
EVIDENCE_DIR=/app/ghostwriter/media/evidence

[[ ! -d "$EVIDENCE_DIR" ]] && mkdir -p "$EVIDENCE_DIR"
[[ ! -d "$AVATAR_DIR" ]] && mkdir -p "$AVATAR_DIR"

python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000
