#!/bin/bash
#Cron script
# acd-ghostwriter/cron

#Run certbot renewal
/usr/bin/certbot renew --quiet

#Copy renewed certs to correct location
cp /etc/letsencrypt/live/mgmt.test.optumshadow.org/privkey.pem /opt/Ghostwriter/ssl/ghostwriter.key.pem
cp /etc/letsencrypt/live/mgmt.test.optumshadow.org/fullchain.pem /opt/Ghostwriter/ssl/ghostwriter.crt.pem

#Activate renewed certs
docker-compose -f /opt/Ghostwriter/production.yml restart nginx