# Generated by Django 4.2.21 on 2026-05-14

# Standard Libraries
import uuid

# Django Imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The user project read-access view optimization originally lived in 0005. It is
# applied here so 0005 can commit API key data updates before this migration adds
# the API key identifier uniqueness constraint.

CREATE_OPTIMIZED_USER_PROJECT_READ_ACCESS_VIEW = """
CREATE OR REPLACE VIEW api_user_project_read_access AS
SELECT
    privileged_users.id AS user_id,
    rolodex_project.id AS project_id
FROM (
    SELECT id
    FROM users_user
    WHERE
        users_user.is_active
        AND (
            users_user.role IN ('admin', 'manager')
            OR users_user.is_staff
            OR users_user.is_superuser
        )
) AS privileged_users
INNER JOIN rolodex_project
    ON TRUE

UNION

SELECT
    rolodex_clientinvite.user_id,
    rolodex_project.id AS project_id
FROM rolodex_clientinvite
INNER JOIN users_user
    ON users_user.id = rolodex_clientinvite.user_id
    AND users_user.is_active
INNER JOIN rolodex_project
    ON rolodex_project.client_id = rolodex_clientinvite.client_id

UNION

SELECT
    rolodex_projectinvite.user_id,
    rolodex_projectinvite.project_id
FROM rolodex_projectinvite
INNER JOIN users_user
    ON users_user.id = rolodex_projectinvite.user_id
    AND users_user.is_active

UNION

SELECT
    rolodex_projectassignment.operator_id AS user_id,
    rolodex_projectassignment.project_id
FROM rolodex_projectassignment
INNER JOIN users_user
    ON users_user.id = rolodex_projectassignment.operator_id
    AND users_user.is_active
"""


CREATE_ORIGINAL_USER_PROJECT_READ_ACCESS_VIEW = """
CREATE OR REPLACE VIEW api_user_project_read_access AS
SELECT DISTINCT
    users_user.id AS user_id,
    rolodex_project.id AS project_id
FROM users_user
CROSS JOIN rolodex_project
WHERE
    users_user.is_active
    AND (
        users_user.role IN ('admin', 'manager')
        OR users_user.is_staff
        OR users_user.is_superuser
        OR EXISTS (
            SELECT 1
            FROM rolodex_clientinvite
            WHERE
                rolodex_clientinvite.user_id = users_user.id
                AND rolodex_clientinvite.client_id = rolodex_project.client_id
        )
        OR EXISTS (
            SELECT 1
            FROM rolodex_projectinvite
            WHERE
                rolodex_projectinvite.user_id = users_user.id
                AND rolodex_projectinvite.project_id = rolodex_project.id
        )
        OR EXISTS (
            SELECT 1
            FROM rolodex_projectassignment
            WHERE
                rolodex_projectassignment.operator_id = users_user.id
                AND rolodex_projectassignment.project_id = rolodex_project.id
        )
    )
"""


APIKEY_IDENTIFIER_CONSTRAINT = "api_apikey_identifier_6e4e2f82_uniq"


def ensure_api_key_identifiers_are_unique(apps, schema_editor):
    schema_editor.execute('LOCK TABLE "api_apikey" IN ACCESS EXCLUSIVE MODE')

    APIKey = apps.get_model("api", "APIKey")
    db_alias = schema_editor.connection.alias
    null_identifier_count = (
        APIKey.objects.using(db_alias).filter(identifier__isnull=True).count()
    )
    if null_identifier_count:
        raise RuntimeError(
            "Cannot add the API key identifier NOT NULL constraint because "
            f"{null_identifier_count} API key record(s) still have NULL "
            "identifiers. Re-run api.0005 or backfill identifiers before "
            "applying api.0006."
        )

    duplicate_identifiers = (
        APIKey.objects.using(db_alias)
        .exclude(identifier__isnull=True)
        .values("identifier")
        .annotate(identifier_count=models.Count("id"))
        .filter(identifier_count__gt=1)
        .order_by("identifier")
    )
    duplicate_identifier_count = duplicate_identifiers.count()
    if duplicate_identifier_count:
        examples = ", ".join(
            str(row["identifier"]) for row in duplicate_identifiers[:5]
        )
        raise RuntimeError(
            "Cannot add the API key identifier UNIQUE constraint because "
            f"{duplicate_identifier_count} duplicate identifier value(s) "
            "exist. Resolve duplicate API key identifiers before applying "
            f"api.0006. Example duplicate identifier(s): {examples}."
        )

    with schema_editor.connection.cursor() as cursor:
        schema_editor.execute(
            'ALTER TABLE "api_apikey" ALTER COLUMN "identifier" SET NOT NULL'
        )
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor, "api_apikey"
        )
        has_unique_identifier = any(
            constraint["unique"] and constraint["columns"] == ["identifier"]
            for constraint in constraints.values()
        )
        if not has_unique_identifier:
            schema_editor.execute(
                'ALTER TABLE "api_apikey" '
                f'ADD CONSTRAINT "{APIKEY_IDENTIFIER_CONSTRAINT}" '
                'UNIQUE ("identifier")'
            )


class CreateModelIfTableMissing(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        with schema_editor.connection.cursor() as cursor:
            existing_tables = schema_editor.connection.introspection.table_names(
                cursor
            )
        if model._meta.db_table in existing_tables:
            return
        schema_editor.create_model(model)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # A pre-split 0004 may have created this table. Keep rollback from
        # dropping a table that can belong to an earlier recorded migration.
        return


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_optimize_user_project_read_access_view"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_api_key_identifiers_are_unique,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="apikey",
                    name="identifier",
                    field=models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                )
            ],
        ),
        CreateModelIfTableMissing(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_graphql_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graphql_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql=CREATE_OPTIMIZED_USER_PROJECT_READ_ACCESS_VIEW,
            reverse_sql=CREATE_ORIGINAL_USER_PROJECT_READ_ACCESS_VIEW,
        ),
    ]
