# Generated by Django 4.2.21 on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_optimize_user_project_read_access_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
