# Generated by Django 2.2.3 on 2020-01-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0008_auto_20191122_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxServerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Enter the IP address to add', verbose_name='IP Address')),
                ('static_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shepherd.StaticServer')),
            ],
            options={
                'verbose_name': 'Auxiliary IP address',
                'verbose_name_plural': 'Auxiliary IP addresses',
                'ordering': ['static_server', 'ip_address'],
            },
        ),
    ]
