# Generated by Django 2.2.3 on 2020-09-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0013_auto_20200825_1947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytype",
            name="activity",
            field=models.CharField(
                help_text="Reason for the use of the asset (e.g. C2, Phishing)", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="auxserveraddress",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Enter the auxiliary IP address for the server",
                null=True,
                verbose_name="IP Address",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="bluecoat_cat",
            field=models.CharField(
                blank=True,
                help_text="Provide the list of categories determined by Bluecoat",
                max_length=255,
                null=True,
                verbose_name="Bluecoat",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="fortiguard_cat",
            field=models.CharField(
                blank=True,
                help_text="Provide the list of categories determined by Fortiguard",
                max_length=255,
                null=True,
                verbose_name="Fortiguard",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="health_dns",
            field=models.CharField(
                blank=True,
                help_text='Enter passive DNS information from VirusTotal - leave blank or enter "Healthy" if you do not know',
                max_length=255,
                null=True,
                verbose_name="DNS Health",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="ibm_xforce_cat",
            field=models.CharField(
                blank=True,
                help_text="Provide the list of categories determined by IBM X-Force",
                max_length=255,
                null=True,
                verbose_name="IBM X-Force",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="mx_toolbox_status",
            field=models.CharField(
                blank=True,
                help_text="Enter the domain spam/blacklist status as determined by MX Toolbox",
                max_length=255,
                null=True,
                verbose_name="MX Toolbox Status",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(help_text="Enter the domain name", max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="domain",
            name="opendns_cat",
            field=models.CharField(
                blank=True,
                help_text="Provide the list of categories determined by OpenDNS",
                max_length=255,
                null=True,
                verbose_name="OpenDNS",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="registrar",
            field=models.CharField(
                blank=True,
                help_text="Enter the name of the registrar where this domain is registered",
                max_length=255,
                null=True,
                verbose_name="Registrar",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="talos_cat",
            field=models.CharField(
                blank=True,
                help_text="Provide the list of categories determined by Cisco Talos",
                max_length=255,
                null=True,
                verbose_name="Cisco Talos",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="trendmicro_cat",
            field=models.CharField(
                blank=True,
                help_text="Provide the list of categories determined by TrendMicro",
                max_length=255,
                null=True,
                verbose_name="TrendMicro",
            ),
        ),
        migrations.AlterField(
            model_name="domainnote",
            name="timestamp",
            field=models.DateField(auto_now_add=True, help_text="Creation timestamp", verbose_name="Timestamp"),
        ),
        migrations.AlterField(
            model_name="domainserverconnection",
            name="endpoint",
            field=models.CharField(
                blank=True,
                help_text="The CDN endpoint used with this link, if any",
                max_length=255,
                null=True,
                verbose_name="CDN Endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="domainserverconnection",
            name="subdomain",
            field=models.CharField(
                blank=True,
                default="*",
                help_text="The subdomain used for this domain record",
                max_length=255,
                null=True,
                verbose_name="Subdomain",
            ),
        ),
        migrations.AlterField(
            model_name="domainstatus",
            name="domain_status",
            field=models.CharField(help_text="Domain status type (e.g. Available)", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="healthstatus",
            name="health_status",
            field=models.CharField(help_text="Health status type (e.g. Healthy, Burned)", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="end_date",
            field=models.DateField(help_text="Select the end date of the project", verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="history",
            name="start_date",
            field=models.DateField(help_text="Select the start date of the project", verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="serverhistory",
            name="end_date",
            field=models.DateField(help_text="Select the end date of the project", verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="serverhistory",
            name="start_date",
            field=models.DateField(help_text="Select the start date of the project", verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="servernote",
            name="timestamp",
            field=models.DateField(auto_now_add=True, help_text="Creation timestamp", verbose_name="Timestamp"),
        ),
        migrations.AlterField(
            model_name="serverprovider",
            name="server_provider",
            field=models.CharField(
                help_text="Name of the server provider (e.g. Amazon Web Services, Azure)", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="serverrole",
            name="server_role",
            field=models.CharField(
                help_text="A role for applied to the use of a server (e.g. Payload Delivery, Redirector)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="serverstatus",
            name="server_status",
            field=models.CharField(help_text="Server status (e.g. Available)", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="staticserver",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Enter the server's name (typically hostname)",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="transientserver",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Enter the server's name (typically hostname)",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="whoisstatus",
            name="whois_status",
            field=models.CharField(
                help_text="WHOIS privacy status (e.g. Enabled, Disabled)", max_length=255, unique=True
            ),
        ),
    ]
