# Generated by Django 3.1.13 on 2021-09-23 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0019_auto_20210706_2242"),
    ]

    operations = [
        migrations.AddField(
            model_name="transientserver",
            name="address",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(
                    help_text="Enter the server IP address", verbose_name="IP Address"
                ),
                default=list,
                size=None,
            ),
        ),
    ]
