# Generated by Django 3.1.13 on 2021-09-23 19:53

# Django Imports
from django.db import migrations


def convert_to_arrayfield(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TransientServer = apps.get_model("shepherd", "TransientServer")
    for server in TransientServer.objects.all():
        server.address = [server.ip_address]
        server.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0020_transientserver_address"),
    ]

    operations = [
        migrations.RunPython(convert_to_arrayfield),
    ]
