# Generated by Django 3.1.13 on 2021-09-23 21:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0021_auto_20210923_1953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transientserver",
            name="address",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(
                    help_text="Enter the server IP address", verbose_name="IP Address"
                ),
                default=list,
                help_text="Enter a comma-separated list of IP addresses",
                size=None,
            ),
        ),
    ]
