# Generated by Django 3.1.13 on 2022-02-01 23:31

# Django Imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0030_auto_20211103_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="categorization",
            field=models.JSONField(
                blank=True,
                help_text="Categories applied to this domain as JSON - e.g., `source:category`",
                null=True,
                verbose_name="Categorization",
            ),
        ),
    ]
