# Generated by Django 3.1.13 on 2022-02-01 23:33

# Standard Libraries
import json

# Django Imports
from django.db import migrations


def convert_to_jsonfield(apps, schema_editor):
    # Convert the to-be-deleted fields to JSON for the ``JSONfield``
    Domain = apps.get_model("shepherd", "Domain")
    for entry in Domain.objects.all():
        categories = {
            "IBM X-Force": entry.ibm_xforce_cat,
            "Talos": entry.talos_cat,
            "Bluecoat": entry.bluecoat_cat,
            "Fortiguard": entry.fortiguard_cat,
            "OpenDNS": entry.opendns_cat,
            "TrendMicro": entry.trendmicro_cat,
            "MX Toolbox": entry.mx_toolbox_status,
        }
        # Dump ``dict`` to ``str``
        cat_json = json.dumps(categories)
        # Load ``str`` as JSON and save it
        entry.categorization = json.loads(cat_json)
        entry.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0031_auto_20220201_2331"),
    ]

    operations = [
        migrations.RunPython(convert_to_jsonfield),
    ]
