# Generated by Django 3.1.13 on 2022-02-03 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0033_delete_old_domain_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="health_dns",
        ),
    ]
