# Generated by Django 3.2.11 on 2022-05-10 19:09

# Django Imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0038_alter_domain_dns_record"),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE shepherd_domainnote ALTER COLUMN timestamp SET DEFAULT CURRENT_TIMESTAMP;"),
        migrations.RunSQL(
            "ALTER TABLE shepherd_servernote ALTER COLUMN timestamp SET DEFAULT CURRENT_TIMESTAMP;",
        ),
    ]
