# Generated by Django 3.2.11 on 2022-07-06 17:09

# Django Imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0040_auto_20220510_1949"),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE shepherd_domain ALTER COLUMN whois_status_id SET DEFAULT 1;"),
        migrations.RunSQL("ALTER TABLE shepherd_domain ALTER COLUMN health_status_id SET DEFAULT 1;"),
        migrations.RunSQL("ALTER TABLE shepherd_domain ALTER COLUMN domain_status_id SET DEFAULT 1;"),
    ]
