# Generated by Django 3.2.19 on 2023-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0044_alter_domain_reset_dns'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
