# Generated by Django 3.2.19 on 2023-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0045_domain_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticserver',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
