# Generated by Django 3.2.19 on 2024-05-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0047_extra_fields_db_default'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE', reverse_sql='SET CONSTRAINTS ALL DEFERRED'),
        migrations.AlterField(
            model_name='domain',
            name='burned_explanation',
            field=models.TextField(blank=True, default='', help_text='Provide details such as how the domain was detected, why it was blacklisted for spam, if it was flagged with a bad category, etc.', verbose_name='Health Explanation'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Use this area to provide notes and thoughts behind its purchase and intended use', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registrar',
            field=models.CharField(blank=True, default='', help_text='Enter the name of the registrar where this domain is registered', max_length=255, verbose_name='Registrar'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='vt_permalink',
            field=models.CharField(blank=True, default='', help_text="VirusTotal's permalink for scan results of this domain", max_length=255, verbose_name='VirusTotal Permalink'),
        ),
        migrations.AlterField(
            model_name='domainnote',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Use this area to add a note to this domain', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='domainserverconnection',
            name='endpoint',
            field=models.CharField(blank=True, default='', help_text='The CDN endpoint used with this link, if any', max_length=255, verbose_name='CDN Endpoint'),
        ),
        migrations.AlterField(
            model_name='domainserverconnection',
            name='subdomain',
            field=models.CharField(blank=True, default='*', help_text='The subdomain used for this domain record', max_length=255, verbose_name='Subdomain'),
        ),
        migrations.AlterField(
            model_name='history',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Use this area to provide project-related notes, such as how the domain will be used/how it worked out', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='serverhistory',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Use this area to provide project-related notes, such as how the server/IP will be used', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='servernote',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Use this area to add a note to this server', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='staticserver',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Enter the server's name (typically hostname)", max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='staticserver',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Use this area to provide server-related notes, such as its designated use or how it can be used', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='transientserver',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Enter the server's name (typically hostname)", max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transientserver',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Use this area to provide project-related notes, such as how the server will be used', verbose_name='Notes'),
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED', reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
