# Generated by Django 3.2.19 on 2024-09-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0049_set_text_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transientserver',
            name='activity_type',
            field=models.ForeignKey(help_text='Select how this VPS will be used', on_delete=django.db.models.deletion.PROTECT, to='shepherd.activitytype'),
        ),
        migrations.AlterField(
            model_name='transientserver',
            name='server_role',
            field=models.ForeignKey(help_text='Select the role this VPS will play', on_delete=django.db.models.deletion.PROTECT, to='shepherd.serverrole'),
        ),
    ]
