# Generated by Django 3.2.19 on 2024-09-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0049_set_text_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transientserver',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Enter the server IP address', verbose_name='IP Address'),
        ),
    ]
