# Generated by Django 3.2.19 on 2024-09-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0050_alter_transientserver_ip_address'),
        ('shepherd', '0050_auto_20240917_1521'),
    ]

    operations = [
    ]
