# Generated by Django 4.2 on 2025-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0051_merge_20240918_1642"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="history",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="serverhistory",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="staticserver",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="transientserver",
            old_name="note",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="domain",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use this area to provide notes and thoughts behind its purchase and intended use",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use this area to provide project-related notes, such as how the domain will be used/how it worked out",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="serverhistory",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use this area to provide project-related notes, such as how the server/IP will be used",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="staticserver",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use this area to provide server-related notes, such as its designated use or how it can be used",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="transientserver",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use this area to provide project-related notes, such as how the server will be used",
                verbose_name="Description",
            ),
        ),
    ]
