# Generated by Django 5.2.14 on 2026-07-22 17:21

# Django Imports
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shepherd", "0052_rename_note_to_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(
                help_text="Enter the domain name",
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_domain_name",
                        message="Enter a valid domain name using letters, numbers, periods, and hyphens.",
                        regex="\\A(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.?\\Z",
                    )
                ],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="staticserver",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Enter the server's name (typically hostname)",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_server_name",
                        message="Enter a valid server name using letters, numbers, periods, underscores, and hyphens.",
                        regex="\\A(?:[A-Za-z0-9](?:[A-Za-z0-9._-]{0,253}[A-Za-z0-9])?)?\\Z",
                    )
                ],
                verbose_name="Name",
            ),
        ),
    ]
