# Generated by Django 2.2.3 on 2020-10-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudservicesconfiguration",
            name="ignore_tag",
            field=models.CharField(
                default="gw_ignore",
                help_text="Ghostwriter will ignore cloud assets with one of these tags (comma-separated list)",
                max_length=255,
                verbose_name="Ignore Tags",
            ),
        ),
    ]
