# Generated by Django 3.0.10 on 2021-01-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0005_auto_20201102_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route53Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('access_key', models.CharField(default='Route53 Access Key', max_length=255)),
                ('secret_access_key', models.CharField(default='Route53 Secret Access Key', max_length=255)),
            ],
            options={
                'verbose_name': 'Route53 Configuration',
            },
        ),
    ]
