# Generated by Django 3.0.10 on 2021-09-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0008_remove_namecheapconfiguration_reset_dns"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudservicesconfiguration",
            name="notification_delay",
            field=models.IntegerField(
                default=7,
                help_text="Number of days to delay cloud monitoring notifications for teardown",
                verbose_name="Notification Delay",
            ),
        ),
    ]
