# Generated by Django 3.2.11 on 2022-11-01 21:47

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0011_alter_slackconfiguration_slack_alert_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "default_timezone",
                    timezone_field.fields.TimeZoneField(
                        default="America/Los_Angeles",
                        help_text="Select a default timezone for clients and projects",
                        verbose_name="Default Timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "General Settings",
            },
        ),
    ]
