# Generated by Django 3.2.16 on 2023-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0014_alter_reportconfiguration_report_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='report_filename',
            field=models.CharField(default='{Y-m-d}_{His} {company} - {client} {assessment_type} Report', help_text='Name of the report file when downloaded that can include the following variables: title, date, company, client, assessment_type, and date format string values', max_length=255, verbose_name='Default Name for Report Downloads'),
        ),
    ]
