# Generated by Django 3.2.19 on 2023-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandcenter", "0015_alter_reportconfiguration_report_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinformation",
            name="company_address",
            field=models.TextField(
                default="14 N Moore St, New York, NY 10013", help_text="Company address to reference in reports"
            ),
        ),
        migrations.AddField(
            model_name="companyinformation",
            name="company_short_name",
            field=models.CharField(
                default="SO", help_text="Abbreviated company name to reference in reports", max_length=255
            ),
        ),
    ]
