# Generated by Django 3.2.19 on 2023-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0016_auto_20230922_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_enable', models.BooleanField(default=False)),
                ('slack_webhook_url', models.CharField(default='https://hooks.slack.com/services/<your_webhook_url>', max_length=255)),
                ('slack_emoji', models.CharField(default=':ghost:', help_text='Emoji used for the avatar wrapped in colons', max_length=255)),
                ('slack_channel', models.CharField(default='#ghostwriter', help_text='Default channel for Slack notifications', max_length=255)),
                ('slack_username', models.CharField(default='Ghostwriter', help_text='Display name for the Slack bot', max_length=255)),
                ('slack_alert_target', models.CharField(blank=True, default='<!here>', help_text='Alert target for the notifications (e.g., <!here>) – blank for no target', max_length=255)),
                ('teams_enable', models.BooleanField(default=False)),
                ('teams_webhook_url', models.CharField(default='https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet#create-incoming-webhooks-1', max_length=255)),
            ],
            options={
                'verbose_name': 'Notifications Configuration',
            },
        ),
        migrations.DeleteModel(
            name='SlackConfiguration',
        ),
    ]
