# Generated by Django 3.2.19 on 2023-10-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0016_auto_20230922_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFieldModel',
            fields=[
                ('model_internal_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model_display_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Extra Field Configuration',
            },
        ),
        migrations.CreateModel(
            name='ExtraFieldSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox'), ('single_line_text', 'Single-Line of Text'), ('rich_text', 'Formatted Text'), ('integer', 'Integer'), ('float', 'Number')], max_length=255)),
                ('target_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandcenter.extrafieldmodel')),
            ],
            options={
                'verbose_name': 'Extra Field',
                'order_with_respect_to': 'target_model',
                'unique_together': {('target_model', 'internal_name')},
            },
        ),
    ]
