# Generated by Django 3.2.19 on 2024-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0017_extrafieldmodel_extrafieldspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafieldspec',
            name='user_default_value',
            field=models.TextField(blank=True, default='', verbose_name='Default Value'),
        ),
    ]
