# Generated by Django 3.2.19 on 2024-02-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandcenter", "0018_extrafieldspec_user_default_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportconfiguration",
            name="target_delivery_date",
            field=models.IntegerField(
                default=5,
                help_text="Number of business days from the project's end date to set as the default target delivery date",
                verbose_name="Target Delivery Date",
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="title_case_captions",
            field=models.BooleanField(
                default=True, help_text="Capitalize the first letter of each word in figure and table captions"
            ),
        ),
    ]
