# Generated by Django 3.2.19 on 2024-02-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0019_auto_20240221_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='title_case_exceptions',
            field=models.CharField(blank=True, default='a,as,at,an,and,of,the,is,to,by,for,in,on,but,or', help_text='Comma-separated list of words to exclude from title case conversion', max_length=255, verbose_name='Title Case Exceptions'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='target_delivery_date',
            field=models.IntegerField(default=7, help_text="Number of business days from the project's end date to set as the default target delivery date", verbose_name='Target Delivery Date'),
        ),
    ]
