# Generated by Django 3.2.19 on 2024-02-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0020_auto_20240221_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='target_delivery_date',
            field=models.IntegerField(default=5, help_text="Number of business days from the project's end date to set as the default target delivery date", verbose_name='Target Delivery Date'),
        ),
    ]
