# Generated by Django 3.2.19 on 2024-02-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0021_alter_reportconfiguration_target_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafieldspec',
            name='user_default_value',
            field=models.TextField(blank=True, default='', verbose_name='Value for New Objects'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='title_case_captions',
            field=models.BooleanField(default=True, help_text='Capitalize the first letter of each word in figure and table captions', verbose_name='Title Case Captions'),
        ),
    ]
