# Generated by Django 3.2.19 on 2024-03-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0022_auto_20240228_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='hostname',
            field=models.CharField(default='ghostwriter.local', help_text='Hostname or IP address for Ghostwriter (used for links in notifications)', max_length=255),
        ),
    ]
