# Generated by Django 3.2.19 on 2024-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0026_report_filename_template_convert_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='project_filename',
            field=models.CharField(default='{{now|format_datetime("Y-m-d_His")}} {{company.name}} - {{client.name}} {{project.project_type}} Report', help_text='Jinja2 template for project filenames. All template variables are available, plus {{now}} and {{company_name}}. The file extension is added to this. Individual templates may override this option.', max_length=255, verbose_name='Default Name for Project Downloads'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='report_filename',
            field=models.CharField(default='{{now|format_datetime("Y-m-d_His")}} {{company.name}} - {{client.name}} {{project.project_type}} Report', help_text='Jinja2 template for report filenames. All template variables are available, plus {{now}} and {{company_name}}. The file extension is added to this. Individual templates may override this option.', max_length=255, verbose_name='Default Name for Report Downloads'),
        ),
    ]
