# Generated by Django 3.2.19 on 2024-04-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0051_merge_20240429_1901'),
        ('commandcenter', '0027_auto_20240422_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='default_docx_template',
            field=models.ForeignKey(blank=True, help_text='Select a default Word template', limit_choices_to={'client__isnull': True, 'doc_type__doc_type__iexact': 'docx'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportconfiguration_docx_set', to='reporting.reporttemplate'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='default_pptx_template',
            field=models.ForeignKey(blank=True, help_text='Select a default PowerPoint template', limit_choices_to={'client__isnull': True, 'doc_type__doc_type__iexact': 'pptx'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportconfiguration_pptx_set', to='reporting.reporttemplate'),
        ),
    ]
