# Generated by Django 3.2.19 on 2024-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0029_auto_20240604_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafieldspec',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('single_line_text', 'Single-Line of Text'), ('rich_text', 'Formatted Text'), ('integer', 'Integer'), ('float', 'Number'), ('json', 'JSON')], max_length=255),
        ),
    ]
