# Generated by Django 3.2.19 on 2024-11-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0030_alter_extrafieldspec_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='table_caption_location',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', help_text='Where to place table captions relative to the table', max_length=10, verbose_name='Table Caption Location'),
        ),
    ]
