# Generated by Django 3.2.19 on 2024-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0031_reportconfiguration_table_caption_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='figure_caption_location',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', help_text='Where to place figure captions relative to the figure', max_length=10, verbose_name='Figure Caption Location'),
        ),
    ]
