# Generated by Django 3.2.19 on 2024-12-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0032_reportconfiguration_figure_caption_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='prefix_figure',
            field=models.CharField(default=' – ', help_text='Unicode characters to place between the label and your figure caption in Word reports (include any desired spaces before and after)', max_length=255, verbose_name='Character Before Figure Captions'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='prefix_table',
            field=models.CharField(default=' – ', help_text='Unicode characters to place between the label and your table caption in Word reports (include any desired spaces before and after)', max_length=255, verbose_name='Character Before Table Titles'),
        ),
    ]
