# Generated by Django 4.2 on 2025-01-10 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0031_alter_generalconfiguration_default_timezone"),
        ("commandcenter", "0033_auto_20241204_1810"),
    ]

    operations = []
