# Generated by Django 3.2.19 on 2025-07-22 20:09

from django.db import migrations, models
import ghostwriter.commandcenter.models


class Migration(migrations.Migration):

    dependencies = [
        ('commandcenter', '0034_bloodhoundconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodhoundconfiguration',
            name='api_root_url',
            field=models.CharField(blank=True, default='', help_text='The URL of the BloodHound instance', max_length=255, validators=[ghostwriter.commandcenter.models.validate_endpoint], verbose_name='BloodHound API URL'),
        ),
    ]
