# Generated by Django 4.2 on 2025-07-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("commandcenter", "0036_bannerconfiguration_and_more"),
        (
            "commandcenter",
            "0037_rename_banner_url_bannerconfiguration_banner_link_and_more",
        ),
        ("commandcenter", "0038_bannerconfiguration_expiry_date"),
        ("commandcenter", "0039_alter_bannerconfiguration_expiry_date"),
        ("commandcenter", "0040_bannerconfiguration_public_banner"),
        ("commandcenter", "0041_alter_bannerconfiguration_public_banner"),
    ]

    dependencies = [
        ("commandcenter", "0035_extrafieldmodel_is_collab_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinformation",
            name="company_address",
            field=models.TextField(
                blank=True,
                default="14 N Moore St, New York, NY 10013",
                help_text="Company address to reference in reports",
            ),
        ),
        migrations.AlterField(
            model_name="companyinformation",
            name="company_email",
            field=models.CharField(
                blank=True,
                default="info@specterops.io",
                help_text="Email address to reference in reports",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="companyinformation",
            name="company_twitter",
            field=models.CharField(
                blank=True,
                default="@specterops",
                help_text="Twitter handle to reference in reports",
                max_length=255,
                verbose_name="Twitter Handle",
            ),
        ),
        migrations.CreateModel(
            name="BannerConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_banner",
                    models.BooleanField(
                        default=False,
                        help_text="Enable the homepage banner to display for all users",
                    ),
                ),
                (
                    "banner_message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Message to display in the banner",
                        max_length=255,
                    ),
                ),
                (
                    "banner_link",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL to link the banner to (leave blank for no link)",
                        max_length=255,
                    ),
                ),
                (
                    "banner_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title to display in the banner",
                        max_length=255,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Select the date when the banner should stop displaying (leave blank if it should not expire)",
                        null=True,
                        verbose_name="Display Until",
                    ),
                ),
                (
                    "public_banner",
                    models.BooleanField(
                        default=False,
                        help_text="Display the banner to all users, including unauthenticated users on the login page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner Configuration",
            },
        ),
    ]
