# Generated by Django 4.2 on 2025-07-29 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0035_bloodhound_project_config"),
        ("commandcenter", "0035_extrafieldmodel_is_collab_editable"),
    ]

    operations = []
