# Generated by Django 4.2 on 2025-07-31 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "commandcenter",
            "0036_bannerconfiguration_and_more_squashed_0041_alter_bannerconfiguration_public_banner",
        ),
        ("commandcenter", "0036_merge_20250729_1731"),
    ]

    operations = []
