# Generated by Django 4.2 on 2025-08-21 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0042_merge_20250731_1842"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloodhoundconfiguration",
            old_name="api_key_id",
            new_name="bloodhound_api_key_id",
        ),
        migrations.RenameField(
            model_name="bloodhoundconfiguration",
            old_name="api_key_token",
            new_name="bloodhound_api_key_token",
        ),
        migrations.RenameField(
            model_name="bloodhoundconfiguration",
            old_name="api_root_url",
            new_name="bloodhound_api_root_url",
        ),
    ]
