# Generated by Django 4.2.16 on 2026-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0044_bloodhoundconfiguration_bloodhound_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportconfiguration",
            name="default_cvss_version",
            field=models.CharField(
                choices=[("3.1", "CVSS v3.1"), ("4.0", "CVSS v4.0")],
                default="3.1",
                help_text="Default CVSS calculator version to display when no user preference is saved in browser local storage",
                max_length=10,
                verbose_name="Default CVSS Calculator Version",
            ),
        ),
    ]
