# Generated by Django 4.2.16 on 2025-12-17 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0038_openaiconfiguration"),
        ("commandcenter", "0044_bloodhoundconfiguration_bloodhound_results"),
    ]

    operations = []
