# Generated by Django 4.2.16 on 2026-04-03 22:36

import django.core.validators
from django.db import migrations, models


def backfill_extra_field_positions(apps, schema_editor):
    ExtraFieldSpec = apps.get_model("commandcenter", "ExtraFieldSpec")

    target_model_ids = (
        ExtraFieldSpec.objects.order_by()
        .values_list("target_model_id", flat=True)
        .distinct()
    )

    for target_model_id in target_model_ids:
        field_specs = list(
            ExtraFieldSpec.objects.filter(target_model_id=target_model_id).order_by("_order", "id")
        )
        for index, field_spec in enumerate(field_specs, start=1):
            ExtraFieldSpec.objects.filter(pk=field_spec.pk).update(position=index)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0045_reportconfiguration_default_cvss_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extrafieldspec",
            options={
                "ordering": ["target_model", "position", "id"],
                "verbose_name": "Extra Field",
            },
        ),
        migrations.AddField(
            model_name="extrafieldspec",
            name="position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Enter the display order for this extra field. Changing it will reorder the other extra fields for this model.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Position",
            ),
        ),
        migrations.RunPython(backfill_extra_field_positions, noop_reverse),
        migrations.AlterOrderWithRespectTo(
            name="extrafieldspec",
            order_with_respect_to=None,
        ),
        migrations.AddConstraint(
            model_name="extrafieldspec",
            constraint=models.UniqueConstraint(
                fields=("target_model", "position"),
                name="commandcenter_extrafieldspec_unique_position_per_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="extrafieldspec",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("position__gte", 1), ("position__isnull", True), _connector="OR"
                ),
                name="commandcenter_extrafieldspec_position_gte_1",
            ),
        ),
    ]
