# Generated by Django 4.2.16 on 2026-04-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "commandcenter",
            "0046_alter_extrafieldspec_options_extrafieldspec_position_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extrafieldspec",
            options={
                "ordering": [
                    "target_model",
                    models.OrderBy(models.F("position"), nulls_last=True),
                    "id",
                ],
                "verbose_name": "Extra Field",
            },
        ),
    ]
