# Generated by Django 4.2.16 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0047_alter_extrafieldspec_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportconfiguration",
            name="outline_tags",
            field=models.CharField(
                blank=True,
                default="report,evidence",
                help_text=(
                    "Comma-separated list of tags to include in generated narrative outlines. "
                    "Use exact tags like report or evidence, wildcard prefixes like cred*, or "
                    "namespaced prefixes like att&ck:. Matching is case-insensitive."
                ),
                max_length=255,
                verbose_name="Narrative Outline Tags",
            ),
        ),
    ]
