# Generated by Django 4.2.16 on 2026-04-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0048_reportconfiguration_outline_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportconfiguration",
            name="outline_tags",
            field=models.CharField(
                blank=True,
                default="report,evidence",
                help_text="Comma-separated list of additional tags to include in generated narrative outlines. Built-in `report` and `evidence` tags are always included and cannot be removed here. Use exact tags like `credentials` or `detection`, wildcard prefixes like `cred*`, or namespaced prefixes like `att&ck:`. Matching is case-insensitive.",
                max_length=255,
                verbose_name="Narrative Outline Tags",
            ),
        ),
    ]
