# Generated by Django 4.2.16 on 2026-04-16 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0051_reportconfiguration_evidence_image_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerconfiguration",
            name="banner_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to link the banner to (leave blank for no link)",
                max_length=255,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
    ]
