# Generated by Django for token lifecycle policy settings.

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commandcenter", "0053_bloodhoundconfiguration_allow_project_fallback"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalconfiguration",
            name="token_extend_requires_rotation",
            field=models.BooleanField(
                default=True,
                help_text="Require API and service token expiry extensions to rotate the opaque credential",
                verbose_name="Require Token Rotation to Extend Expiry",
            ),
        ),
        migrations.AddField(
            model_name="generalconfiguration",
            name="token_max_lifetime_days",
            field=models.PositiveIntegerField(
                default=365,
                help_text="Maximum allowed lifetime for new API and service token expiries",
                validators=[MinValueValidator(1)],
                verbose_name="Maximum Token Lifetime in Days",
            ),
        ),
    ]
