# Generated by Django 2.2.3 on 2019-09-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0003_auto_20190828_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectobjective',
            name='status',
            field=models.ForeignKey(help_text='Set the initial status for this objective', on_delete=django.db.models.deletion.PROTECT, to='rolodex.ObjectiveStatus'),
        ),
    ]
