# Generated by Django 3.0.10 on 2021-01-22 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0007_auto_20201027_1914"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectScope",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Provide a descriptive name for this list (e.g., External IPs, Cardholder Data Environment)",
                        max_length=255,
                        null=True,
                        verbose_name="Scope Name",
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        blank=True,
                        help_text="Provide a list of IP addresses, ranges, hostnames, or a mix with each entry on a new line",
                        null=True,
                        verbose_name="Scope",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Provide a brief description of this list",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "disallowed",
                    models.BooleanField(
                        default=False,
                        help_text="Flag this list as off limits / not to be touched",
                        verbose_name="Disallowed",
                    ),
                ),
                (
                    "requires_caution",
                    models.BooleanField(
                        default=False,
                        help_text="Flag this list as requiring caution or prior warning before testing",
                        verbose_name="Requires Caution",
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rolodex.Project")),
            ],
            options={
                "verbose_name": "Project scope list",
                "verbose_name_plural": "Project scope lists",
                "ordering": ["project", "name"],
            },
        ),
    ]
