# Generated by Django 3.0.10 on 2021-02-04 21:47

import django.db.models.deletion
from django.db import migrations, models

import ghostwriter.rolodex.models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0010_auto_20210204_1957"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSubTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "task",
                    models.TextField(
                        blank=True, help_text="Provide a concise objective", null=True, verbose_name="Task"
                    ),
                ),
                (
                    "complete",
                    models.BooleanField(
                        default=False, help_text="Mark the objective as complete", verbose_name="Completed"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Provide a deadline for this objective",
                        max_length=12,
                        null=True,
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rolodex.ProjectObjective"),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=ghostwriter.rolodex.models.ProjectSubTask.get_status,
                        help_text="Set the status for this objective",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rolodex.ObjectiveStatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objective sub-task",
                "verbose_name_plural": "Objective sub-tasks",
                "ordering": ["parent", "complete", "deadline", "status", "task"],
            },
        ),
    ]
