# Generated by Django 3.0.10 on 2021-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0012_auto_20210211_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsubtask",
            name="marked_complete",
            field=models.DateField(
                blank=True, help_text="Date the task was marked complete", null=True, verbose_name="Marked Complete"
            ),
        ),
    ]
