# Generated by Django 3.0.10 on 2021-02-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0015_auto_20210219_2204"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectivePriority",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weight",
                    models.IntegerField(
                        default=1,
                        help_text="Weight for sorting this priority when viewing objectives (lower numbers are higher priority)",
                        verbose_name="Priority Weight",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        help_text="Objective's priority", max_length=255, unique=True, verbose_name="Objective Priority"
                    ),
                ),
            ],
            options={
                "verbose_name": "Objective priority",
                "verbose_name_plural": "Objective priorities",
                "ordering": ["weight", "priority"],
            },
        ),
        migrations.AlterModelOptions(
            name="projectobjective",
            options={
                "ordering": ["project", "complete", "priority__weight", "deadline", "status", "objective"],
                "verbose_name": "Project objective",
                "verbose_name_plural": "Project objectives",
            },
        ),
        migrations.AddField(
            model_name="projectobjective",
            name="priority",
            field=models.ForeignKey(
                help_text="Assign a priority category",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rolodex.ObjectivePriority",
            ),
        ),
    ]
