# Generated by Django 3.0.10 on 2021-02-27 02:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0017_projectobjective_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectobjective",
            options={
                "ordering": ["project", "position", "complete", "priority__weight", "deadline", "status", "objective"],
                "verbose_name": "Project objective",
                "verbose_name_plural": "Project objectives",
            },
        ),
    ]
