# Generated by Django 3.0.10 on 2021-03-03 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0018_auto_20210227_0228"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["start_date", "end_date", "client", "project_type"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
