# Generated by Django 3.1.13 on 2021-09-23 00:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0022_auto_20210923_0011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_time",
            field=models.TimeField(
                blank=True,
                default=datetime.time(17, 0),
                help_text="Select the end time for each day",
                null=True,
                verbose_name="End Time",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_time",
            field=models.TimeField(
                blank=True,
                default=datetime.time(9, 0),
                help_text="Select the start time for each day",
                null=True,
                verbose_name="Start Time",
            ),
        ),
    ]
