# Generated by Django 3.1.13 on 2021-09-23 15:08

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0023_auto_20210923_0038"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontact",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                default="America/Los_Angeles", help_text="The contact's timezone", verbose_name="Contact's Timezone"
            ),
        ),
    ]
