# Generated by Django 3.1.13 on 2021-09-23 15:40

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0024_clientcontact_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcontact",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                default="America/Los_Angeles", help_text="The contact's timezone", verbose_name="Timezone"
            ),
        ),
    ]
