# Generated by Django 3.1.13 on 2021-11-09 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0025_auto_20210923_1540"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-start_date", "end_date", "client", "project_type"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
