# Generated by Django 3.2.11 on 2022-10-07 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0033_auto_20221006_1927"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deconfliction",
            options={
                "ordering": ["project", "-created_at", "status__weight", "title"],
                "verbose_name": "Project deconfliction",
                "verbose_name_plural": "Project deconflictions",
            },
        ),
    ]
