# Generated by Django 3.2.11 on 2022-10-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0035_auto_20221007_1627"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiteCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "issued",
                    models.DateTimeField(
                        help_text="Date and time the client issued this white card", verbose_name="Issued"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Provide a descriptive headline for this white card (e.g., a username, hostname, or short sentence",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Provide a brief description of this white card",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rolodex.project")),
            ],
            options={
                "verbose_name": "Project white card",
                "verbose_name_plural": "Project white cards",
                "ordering": ["project", "-issued", "title"],
            },
        ),
    ]
