# Generated by Django 3.2.11 on 2022-12-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0038_auto_20221122_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttarget',
            name='note',
            field=models.TextField(blank=True, help_text='Provide additional information about the target or its environment', null=True, verbose_name='Notes'),
        ),
    ]
