# Generated by Django 3.2.16 on 2023-01-10 23:31

from django.db import migrations, models
import ghostwriter.rolodex.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0039_alter_projecttarget_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttarget',
            name='ip_address',
            field=models.CharField(blank=True, help_text="Enter the target's IP address", max_length=255, null=True, validators=[ghostwriter.rolodex.validators.validate_ip_range], verbose_name='IP Address'),
        ),
    ]
