# Generated by Django 3.2.16 on 2023-01-10 23:47

from django.db import migrations, models
import ghostwriter.rolodex.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0040_alter_projecttarget_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttarget',
            name='compromised',
            field=models.BooleanField(default=False, help_text='Flag this target as compromised', verbose_name='Compromised'),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='hostname',
            field=models.CharField(blank=True, help_text="Provide the target's hostname, fully qualified domain name, or other identifier", max_length=255, null=True, verbose_name='Hostname / FQDN'),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Enter the IP address or range of the target host(s)', max_length=45, null=True, validators=[ghostwriter.rolodex.validators.validate_ip_range], verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='note',
            field=models.TextField(blank=True, help_text='Provide additional information about the target(s) or the environment', null=True, verbose_name='Notes'),
        ),
    ]
