# Generated by Django 3.2.19 on 2023-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0042_projectcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='primary',
            field=models.BooleanField(default=False, help_text='Flag this contact as the primary point of contact / report recipient for the project', verbose_name='Primary Contact'),
        ),
    ]
