# Generated by Django 3.2.19 on 2023-09-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0043_projectcontact_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='note',
            field=models.TextField(blank=True, help_text='Provide additional information about the contact', null=True, verbose_name='Contact Note'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='note',
            field=models.TextField(blank=True, help_text='Provide additional information about the contact', null=True, verbose_name='Contact Note'),
        ),
    ]
