# Generated by Django 3.2.19 on 2023-09-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0044_auto_20230901_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
