# Generated by Django 3.2.19 on 2024-01-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0044_auto_20230901_1655"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION is_timezone() RETURNS TRIGGER as $$
            BEGIN
                IF EXISTS(SELECT *
                    FROM pg_timezone_names
                    WHERE LOWER(name) = LOWER(NEW.timezone)
                ) THEN
                    RETURN NEW;
                ELSE
                    RAISE EXCEPTION 'Invalid timezone: "%"',NEW.timezone;
                END IF;
            END;
            $$ language plpgsql STABLE;
        """
        ),
        migrations.RunSQL(
            """
            DO $$
            DECLARE
                t TEXT;
            BEGIN
                FOR t IN
                    SELECT table_name FROM information_schema.columns WHERE column_name = 'timezone'
                LOOP
                    EXECUTE format('DROP TRIGGER IF EXISTS check_timezone_trigger on %I', t,t);
                END loop;
            END;
            $$ language 'plpgsql';
        """
        ),
        migrations.RunSQL(
            """
            DO $$
            DECLARE
                t TEXT;
            BEGIN
                FOR t IN
                    SELECT table_name FROM information_schema.columns WHERE column_name = 'timezone'
                LOOP
                    EXECUTE format('CREATE TRIGGER check_timezone_trigger
                                BEFORE INSERT OR UPDATE ON %I
                                FOR EACH ROW EXECUTE PROCEDURE is_timezone()', t,t);
                END loop;
            END;
            $$ language 'plpgsql';
        """
        ),
        migrations.RunSQL(
            """ALTER TABLE rolodex_projectcontact ALTER COLUMN "primary" SET DEFAULT FALSE;""",
        ),
        migrations.RunSQL(
            "ALTER TABLE rolodex_projectcontact ALTER COLUMN timezone SET DEFAULT 'America/Los_Angeles';",
        ),
    ]
