# Generated by Django 3.2.19 on 2024-01-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0046_client_extra_fields'),
        ('rolodex', '0047_auto_20240112_0004'),
    ]

    operations = [
    ]
