# Generated by Django 3.2.19 on 2025-07-22 20:09

from django.db import migrations, models
import ghostwriter.commandcenter.models


class Migration(migrations.Migration):

    dependencies = [
        ('rolodex', '0052_projectobjective_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bloodhound_api_key_id',
            field=models.CharField(blank=True, default='', help_text='The ID portion of a BloodHound API Key', max_length=255, verbose_name='BloodHound API Key ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='bloodhound_api_key_token',
            field=models.CharField(blank=True, default='', help_text='The token portion of a BloodHound API Key', max_length=255, verbose_name='BloodHound API Key Token'),
        ),
        migrations.AddField(
            model_name='project',
            name='bloodhound_api_root_url',
            field=models.CharField(blank=True, default='', help_text='The URL of the BloodHound instance', max_length=255, validators=[ghostwriter.commandcenter.models.validate_endpoint], verbose_name='BloodHound API URL'),
        ),
    ]
