# Generated by Django 4.2 on 2025-09-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0052_projectobjective_result"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="note",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Provide additional information about the project and planning",
                verbose_name="Description",
            ),
        ),
    ]
