# Generated by Django 4.2 on 2025-10-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0052_projectobjective_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                blank=True,
                height_field="logo_height",
                help_text="Image to use for reporting",
                null=True,
                upload_to="",
                verbose_name="Client Logo",
                width_field="logo_width",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_height",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="Logo Height"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_width",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="Logo Width"
            ),
        ),
    ]
