# Generated by Django 4.2 on 2025-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0053_rename_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="collab_note",
            field=models.TextField(
                blank=True, default="", verbose_name="Collaborative Notes"
            ),
        ),
    ]
