# Generated by Django 4.2 on 2025-10-23 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0053_client_logo"),
        ("rolodex", "0054_project_bloodhound_results"),
    ]

    operations = []
