# Generated by Django 4.2 on 2025-10-01 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0054_project_bloodhound_results"),
        ("rolodex", "0054_project_collab_note"),
    ]

    operations = []
