# Generated by Django 4.2 on 2025-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0056_project_collab_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="clientcontact",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="projectassignment",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="projectcontact",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="projecttarget",
            old_name="note",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="client",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Describe the client or provide some additional information",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Provide additional information about the contact",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Provide additional information about the project role and assignment",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontact",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Provide additional information about the contact",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="projecttarget",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Provide additional information about the target(s) or the environment",
                verbose_name="Description",
            ),
        ),
    ]
