# Generated by Django 4.2.16 on 2025-10-23 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0055_merge_20251023_1349"),
        ("rolodex", "0057_rename_note_to_description"),
    ]

    operations = []
