# Generated by Django 4.2.16 on 2025-10-27 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0058_merge_20251023_2125"),
        ("rolodex", "0058_merge_20251023_2152"),
    ]

    operations = []
