# Generated by Django 4.2.16 on 2026-03-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0059_merge_20251027_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontact",
            name="primary",
            field=models.BooleanField(
                default=False,
                help_text="Flag this contact as the primary point of contact for the client",
                verbose_name="Primary Contact",
            ),
        ),
    ]
