# Generated by Django 5.1.2 on 2026-04-01

# Django Imports
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_project_role_positions(apps, schema_editor):
    ProjectRole = apps.get_model("rolodex", "ProjectRole")

    for position, role in enumerate(ProjectRole.objects.order_by("id"), start=1):
        ProjectRole.objects.filter(pk=role.pk).update(position=position)


def assign_missing_project_assignment_roles(apps, schema_editor):
    ProjectAssignment = apps.get_model("rolodex", "ProjectAssignment")
    ProjectRole = apps.get_model("rolodex", "ProjectRole")

    fallback_role = ProjectRole.objects.order_by("position", "id").first()
    missing_role_assignments = ProjectAssignment.objects.filter(role__isnull=True)

    if not missing_role_assignments.exists():
        return

    if fallback_role is None:
        raise RuntimeError(
            "Cannot migrate ProjectAssignment.role to non-null because no ProjectRole entries exist."
        )

    missing_role_assignments.update(role=fallback_role)


class Migration(migrations.Migration):

    dependencies = [
        ("rolodex", "0060_alter_clientcontact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrole",
            name="position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Enter the display order for this project role",
                null=True,
                verbose_name="Position",
            ),
        ),
        migrations.RunPython(backfill_project_role_positions, migrations.RunPython.noop),
        migrations.RunPython(assign_missing_project_assignment_roles, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="projectassignment",
            options={
                "ordering": [
                    "project",
                    "role__position",
                    "operator__name",
                    "operator__username",
                ],
                "verbose_name": "Project assignment",
                "verbose_name_plural": "Project assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="projectrole",
            options={
                "ordering": ["position", "project_role"],
                "verbose_name": "Project role",
                "verbose_name_plural": "Project roles",
            },
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="role",
            field=models.ForeignKey(
                help_text="Select a role that best describes the selected user's role in this project",
                on_delete=django.db.models.deletion.PROTECT,
                to="rolodex.projectrole",
            ),
        ),
        migrations.AlterField(
            model_name="projectrole",
            name="position",
            field=models.PositiveIntegerField(
                help_text="Enter the display order for this project role",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Position",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrole",
            constraint=models.UniqueConstraint(
                fields=("position",),
                name="rolodex_projectrole_unique_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrole",
            constraint=models.CheckConstraint(
                check=models.Q(("position__gte", 1)),
                name="rolodex_projectrole_position_gte_1",
            ),
        ),
    ]
