# Generated by Django 4.2.16 on 2026-01-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0062_projectcollabnote_timestamps_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCollabNoteField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[("rich_text", "Rich Text"), ("image", "Image")],
                        default="rich_text",
                        help_text="Type of content in this field",
                        max_length=10,
                        verbose_name="Field Type",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML content for rich text fields",
                        verbose_name="Content",
                    ),
                ),
                (
                    "image_width",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Image Width",
                    ),
                ),
                (
                    "image_height",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Image Height",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        height_field="image_height",
                        help_text="Image file for image fields",
                        null=True,
                        upload_to="collab_note_images/%Y/%m/%d/",
                        verbose_name="Image",
                        width_field="image_width",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order within note (lower values first)",
                        verbose_name="Position",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note",
                    models.ForeignKey(
                        help_text="The note this field belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="rolodex.projectcollabnote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project collaborative note field",
                "verbose_name_plural": "Project collaborative note fields",
                "ordering": ["note", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectcollabnotefield",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("field_type", "rich_text"), ("image", "")),
                    models.Q(
                        ("field_type", "image"), models.Q(("image", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="field_type_matches_content",
            ),
        ),
    ]
