# Generated by Django 4.2.16 on 2026-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0062_alter_project_bloodhound_fields_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="collab_note",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Collaborative Notes"
            ),
        ),
    ]
