# Generated by Django 4.2.16 on 2026-03-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0062_migrate_collab_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcollabnote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectcollabnotefield",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
