# Generated by Django 4.2.16 on 2026-01-16 21:05

from django.db import migrations


def migrate_note_content_to_fields(apps, schema_editor):
    """
    Migrate existing content from ProjectCollabNote.content to a new
    ProjectCollabNoteField for each note that has content.
    """
    ProjectCollabNote = apps.get_model("rolodex", "ProjectCollabNote")
    ProjectCollabNoteField = apps.get_model("rolodex", "ProjectCollabNoteField")

    notes_with_content = ProjectCollabNote.objects.filter(node_type="note").exclude(content="")

    for note in notes_with_content:
        # Create a rich_text field with the existing content at position 0
        ProjectCollabNoteField.objects.create(
            note=note,
            field_type="rich_text",
            content=note.content,
            position=0,
        )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: copy field content back to note.content.
    Only copies the first rich_text field.
    """
    ProjectCollabNote = apps.get_model("rolodex", "ProjectCollabNote")
    ProjectCollabNoteField = apps.get_model("rolodex", "ProjectCollabNoteField")

    for note in ProjectCollabNote.objects.filter(node_type="note"):
        # Get the first rich_text field
        first_field = note.fields.filter(field_type="rich_text").order_by("position").first()
        if first_field:
            note.content = first_field.content
            note.save()


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0063_projectcollabnotefield_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_note_content_to_fields, reverse_migration),
    ]
