# Generated by Django 4.2.16 on 2025-12-17 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0059_merge_20251027_1706"),
        ("rolodex", "0096_add_client_logos"),
    ]

    operations = []
