# Generated by Django 4.2.16 on 2025-12-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0097_merge_0059_merge_20251027_1706_0096_add_client_logos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adthresholdmapping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a logo to be used for cover pages",
                null=True,
                upload_to="client_logos/",
                verbose_name="Client Logo",
            ),
        ),
        migrations.AlterField(
            model_name="dnscapmapping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dnsfindingmapping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dnsrecommendationmapping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dnssoacapmapping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="generalcapmapping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="passwordcapmapping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
