# Generated by Django 3.2.19 on 2023-08-18 22:57

# Django Imports
from django.conf import settings
from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={
            "domain": "ghostwriter.local",
            "name": "Ghostwriter",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0006_auto_20210922_2325"),
    ]

    operations = [migrations.RunPython(update_site_forward)]
