# Generated by Django 2.2.3 on 2020-06-13 17:40

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rolodex", "0005_auto_20191122_2304"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oplog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Select the project that will own this oplog",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rolodex.Project",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="OplogEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(auto_now_add=True)),
                (
                    "source_ip",
                    models.CharField(
                        blank=True,
                        help_text="Provide the source hostname / IP from which the command originated.",
                        max_length=50,
                        verbose_name="Source IP / Hostname",
                    ),
                ),
                (
                    "dest_ip",
                    models.CharField(
                        blank=True,
                        help_text="Provide the destination hostname / ip on which the command was ran.",
                        max_length=50,
                        verbose_name="Destination IP/Hostname",
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        blank=True,
                        help_text="The tool used to execute the action",
                        max_length=50,
                        verbose_name="Tool name",
                    ),
                ),
                (
                    "user_context",
                    models.CharField(
                        blank=True,
                        help_text="The user context that executed the command",
                        max_length=50,
                        verbose_name="User Context",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True, help_text="The command that was executed", max_length=50, verbose_name="Command"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A description of why the command was executed and expected results.",
                        max_length=50,
                        verbose_name="Description",
                    ),
                ),
                (
                    "output",
                    tinymce.models.HTMLField(
                        blank=True, help_text="The output of the executed command", null=True, verbose_name="Output"
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        help_text="Any additional comments or useful information.",
                        max_length=50,
                        verbose_name="Comments",
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(
                        blank=True,
                        help_text="The operator that performed the action.",
                        max_length=50,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "oplog_id",
                    models.ForeignKey(
                        help_text="Select which log to which this entry will be inserted.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oplog.Oplog",
                    ),
                ),
            ],
        ),
    ]
