# Generated by Django 2.2.3 on 2020-08-25 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oplogentry",
            name="command",
            field=models.TextField(blank=True, help_text="The command that was executed", verbose_name="Command"),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="comments",
            field=models.TextField(
                blank=True, help_text="Any additional comments or useful information.", verbose_name="Comments"
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description of why the command was executed and expected results.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="dest_ip",
            field=models.TextField(
                blank=True,
                help_text="Provide the destination hostname / ip on which the command was ran.",
                verbose_name="Destination IP/Hostname",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="oplog_id",
            field=models.ForeignKey(
                help_text="Select which log to which this entry will be inserted.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="oplog.Oplog",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="output",
            field=models.TextField(
                blank=True, help_text="The output of the executed command", null=True, verbose_name="Output"
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="source_ip",
            field=models.TextField(
                blank=True,
                help_text="Provide the source hostname / IP from which the command originated.",
                verbose_name="Source IP / Hostname",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="tool",
            field=models.TextField(
                blank=True, help_text="The tool used to execute the action", verbose_name="Tool name"
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="user_context",
            field=models.TextField(
                blank=True, help_text="The user context that executed the command", verbose_name="User Context"
            ),
        ),
    ]
