# Generated by Django 3.0.10 on 2021-07-29 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplog", "0002_auto_20200825_2127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oplog",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="operator_name",
            field=models.CharField(
                blank=True, help_text="The operator that performed the action.", max_length=255, verbose_name="Operator"
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="oplog_id",
            field=models.ForeignKey(
                help_text="Select the log to which this entry will be inserted.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="oplog.Oplog",
            ),
        ),
    ]
