# Generated by Django 3.2.11 on 2022-02-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplog", "0003_auto_20210729_2132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oplog",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
