# Generated by Django 3.2.11 on 2022-10-07 18:50

# Django Imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplog", "0005_auto_20220629_1802"),
    ]

    operations = [
        migrations.AddField(
            model_name="oplog",
            name="mute_notifications",
            field=models.BooleanField(default=False, help_text="Mute activity monitoring notifications for this log"),
        ),
        migrations.RunSQL(
            "ALTER TABLE oplog_oplog ALTER COLUMN mute_notifications SET DEFAULT FALSE;",
        ),
    ]
