# Generated by Django 3.2.11 on 2022-12-06 22:59

# Django Imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplog", "0007_oplogentry_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oplogentry",
            name="dest_ip",
            field=models.CharField(
                blank=True,
                help_text="Provide the destination hostname / ip on which the command was ran.",
                max_length=255,
                null=True,
                verbose_name="Destination IP / Hostname",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="end_date",
            field=models.DateTimeField(
                blank=True, help_text="The date and time the action concluded", null=True, verbose_name="End Date"
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="source_ip",
            field=models.CharField(
                blank=True,
                help_text="Provide the source hostname / IP from which the command originated.",
                max_length=255,
                null=True,
                verbose_name="Source IP / Hostname",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="start_date",
            field=models.DateTimeField(
                blank=True, help_text="The date and time the action began", null=True, verbose_name="Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="tool",
            field=models.CharField(
                blank=True,
                help_text="The tool used to execute the action",
                max_length=255,
                null=True,
                verbose_name="Tool Name",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="user_context",
            field=models.CharField(
                blank=True,
                help_text="The user context that executed the command",
                max_length=255,
                null=True,
                verbose_name="User Context",
            ),
        ),
    ]
