# Generated by Django 3.2.11 on 2022-12-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oplog", "0008_auto_20221206_2259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oplogentry",
            name="command",
            field=models.TextField(
                blank=True, help_text="Provide the command you executed.", null=True, verbose_name="Command"
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description of why you executed the command.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Provide the date and time the action concluded.",
                null=True,
                verbose_name="End Date",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="output",
            field=models.TextField(
                blank=True, help_text="The output of the executed command.", null=True, verbose_name="Output"
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Provide the date and time the action began.",
                null=True,
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="tool",
            field=models.CharField(
                blank=True,
                help_text="Name the tool you used to execute the action.",
                max_length=255,
                null=True,
                verbose_name="Tool Name",
            ),
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="user_context",
            field=models.CharField(
                blank=True,
                help_text="The user context under which th command executed.",
                max_length=255,
                null=True,
                verbose_name="User Context",
            ),
        ),
    ]
