# Generated by Django 3.2.16 on 2023-03-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0009_auto_20221206_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplogentry',
            name='user_context',
            field=models.CharField(blank=True, help_text='The user context under which the command executed.', max_length=255, null=True, verbose_name='User Context'),
        ),
    ]
