# Generated by Django 3.2.11 on 2022-12-12 23:54

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("oplog", "0009_auto_20221206_2306"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaggedOplogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_object",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="oplog.oplogentry"),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oplog_taggedoplogentry_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="oplogentry",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="oplog.TaggedOplogEntry",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
