# Generated by Django 3.2.16 on 2023-03-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0010_alter_oplogentry_user_context'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oplog',
            options={'ordering': ['id', 'project', 'name'], 'verbose_name': 'Activity log', 'verbose_name_plural': 'Activity logs'},
        ),
        migrations.AlterModelOptions(
            name='oplogentry',
            options={'ordering': ['-start_date', '-end_date', 'oplog_id'], 'verbose_name': 'Activity log entry', 'verbose_name_plural': 'Activity log entries'},
        ),
    ]
