# Generated by Django 3.2.19 on 2023-10-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0011_auto_20230323_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='oplogentry',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
