# Generated by Django 3.2.19 on 2023-12-08 21:34

from django.db import migrations
import ghostwriter.oplog.models


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0011_auto_20230323_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplog',
            name='name',
            field=ghostwriter.oplog.models.NoLengthLimitCharField(),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='dest_ip',
            field=ghostwriter.oplog.models.NoLengthLimitCharField(blank=True, help_text='Provide the destination hostname / ip on which the command was ran.', null=True, verbose_name='Destination IP / Hostname'),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='operator_name',
            field=ghostwriter.oplog.models.NoLengthLimitCharField(blank=True, help_text='The operator that performed the action.', null=True, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='source_ip',
            field=ghostwriter.oplog.models.NoLengthLimitCharField(blank=True, help_text='Provide the source hostname / IP from which the command originated.', null=True, verbose_name='Source IP / Hostname'),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='tool',
            field=ghostwriter.oplog.models.NoLengthLimitCharField(blank=True, help_text='Name the tool you used to execute the action.', null=True, verbose_name='Tool Name'),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='user_context',
            field=ghostwriter.oplog.models.NoLengthLimitCharField(blank=True, help_text='The user context under which the command executed.', null=True, verbose_name='User Context'),
        ),
    ]
