# Generated by Django 3.2.19 on 2023-12-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0012_auto_20231208_2134'),
        ('oplog', '0012_auto_20231211_2154'),
    ]

    operations = [
    ]
