# Generated by Django 3.2.19 on 2023-12-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0012_oplogentry_extra_fields'),
        ('oplog', '0013_merge_0012_auto_20231208_2134_0012_auto_20231211_2154'),
    ]

    operations = [
    ]
