# Generated by Django 3.2.19 on 2024-04-02 18:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0014_merge_20231215_1939'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oplogentry',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('source_ip', 'dest_ip', 'tool', 'command', 'description', 'output', 'comments', 'operator_name', config='english'), name='oplog_fts'),
        ),
    ]
