# Generated by Django 3.2.19 on 2024-04-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0015_extra_fields_db_default'),
        ('oplog', '0015_oplogentry_oplog_fts'),
    ]

    operations = [
    ]
