# Generated by Django 3.2.19 on 2024-05-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oplog', '0017_auto_20240516_1722'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='oplogentry',
            name='oplog_fts',
        ),
    ]
