# Generated by Django 4.2.16 on 2026-03-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0065_reportobservationlink_complete"),
        ("oplog", "0019_set_text_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="OplogEntryEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        help_text="The evidence file linked to this oplog entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oplog_entry_links",
                        to="reporting.evidence",
                    ),
                ),
                (
                    "oplog_entry",
                    models.ForeignKey(
                        help_text="The oplog entry this evidence is attached to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="oplog.oplogentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oplog entry evidence link",
                "verbose_name_plural": "Oplog entry evidence links",
                "ordering": ["-id"],
                "unique_together": {("oplog_entry", "evidence")},
            },
        ),
    ]
