# Generated by Django 4.2.16 on 2026-03-17 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ghostwriter.oplog.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oplog", "0020_oplogentryevidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="OplogEntryRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recording_file",
                    models.FileField(
                        max_length=255,
                        upload_to=ghostwriter.oplog.models.set_recording_upload_destination,
                    ),
                ),
                (
                    "uploaded_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time the recording was uploaded.",
                        verbose_name="Upload Date",
                    ),
                ),
                (
                    "oplog_entry",
                    models.OneToOneField(
                        help_text="The oplog entry this recording is attached to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="oplog.oplogentry",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who uploaded this recording.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Oplog entry recording",
                "verbose_name_plural": "Oplog entry recordings",
                "ordering": ["-uploaded_date"],
            },
        ),
    ]
