# Generated by Django 4.2.16 on 2026-03-20 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oplog", "0021_oplogentryrecording"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oplogentryevidence",
            options={
                "ordering": ["-id"],
                "verbose_name": "Activity log entry evidence link",
                "verbose_name_plural": "Activity log entry evidence links",
            },
        ),
        migrations.AlterModelOptions(
            name="oplogentryrecording",
            options={
                "ordering": ["-uploaded_date"],
                "verbose_name": "Activity log entry recording",
                "verbose_name_plural": "Activity log entry recordings",
            },
        ),
    ]
