# Generated by Django 2.2.3 on 2019-07-25 21:25

from django.db import migrations, models

import ghostwriter.home.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "avatar",
                    models.ImageField(
                        default="images/user_avatars/default.png",
                        upload_to=ghostwriter.home.models.UserProfile.set_upload_destination,
                    ),
                ),
            ],
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "User profiles",
                "ordering": ["user"],
            },
        ),
    ]
