# Generated by Django 2.2.3 on 2019-07-29 22:13

from django.db import migrations, models

import ghostwriter.home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(default=None, upload_to=ghostwriter.home.models.UserProfile.set_upload_destination),
        ),
    ]
