# Generated by Django 3.1.13 on 2022-01-25 23:58

from django.db import migrations, models

import ghostwriter.home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_auto_20190729_2213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, upload_to=ghostwriter.home.models.UserProfile.set_upload_destination
            ),
        ),
    ]
