# Generated by Django 3.2.19 on 2025-04-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_quickstart',
            field=models.BooleanField(default=False),
        ),
    ]
