# Generated by Django 5.1.7 on 2026-08-10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_userprofile_hide_quickstart"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardExceptionDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=32, unique=True)),
                ("dismissed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="cleared_dashboard_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dashboard exception dismissal",
                "verbose_name_plural": "dashboard exception dismissals",
                "ordering": ["-dismissed_at"],
            },
        ),
    ]
