"""This contains utilities for managing and converting models."""

# Standard Libraries
from itertools import chain
from typing import Optional, Type

# Django Imports
import django
from django.db import transaction
from django.db.models import ForeignKey, Q


def to_dict(instance: django.db.models.Model, include_id: bool = False, resolve_fk: bool = False) -> dict:
    """
    Converts a model instance to a dictionary with only the desirable field
    data. Extra fields provided by ``.__dict__``, like ``_state``, are removed.

    Ref: https://stackoverflow.com/questions/21925671/convert-django-model-object-to-dict-with-all-of-the-fields-intact

    **Parameters**

    ``instance``
        Instance of ``django.db.models.Model``
    ``include_id``
        Whether to include the ``id`` field in the dictionary (Default: False)
    ``resolve_fk``
        Whether to resolve foreign key fields to an object (Default: False)
    """
    opts = instance._meta
    data = {}
    for f in chain(opts.concrete_fields, opts.private_fields):
        data[f.name] = f.value_from_object(instance)
        if isinstance(f, ForeignKey) and resolve_fk:
            fk_id = f.value_from_object(instance)
            data[f.name] = f.related_model.objects.get(id=fk_id)
    for f in opts.many_to_many:
        data[f.name] = [i.id for i in f.value_from_object(instance)]
    if not include_id:
        del data["id"]
    return data


def _clamp_position(position: Optional[int], count: int) -> int:
    """Return a one-based position that fits inside a group of findings."""
    if count < 1:
        return 1
    if position is None:
        return count
    return min(max(position, 1), count)


def normalize_finding_positions(
    model: Type[django.db.models.Model],
    report_id: int,
    severity_id: int,
    moving_instance_id: Optional[int] = None,
    target_position: Optional[int] = None,
) -> None:
    """
    Normalise report finding positions for a single report/severity group.

    Ordering uses ``position, id`` so duplicate positions converge
    deterministically. Updates are emitted only for rows that need to change,
    allowing Hasura events generated by this function to become no-ops.
    """
    report_model = model._meta.get_field("report").related_model
    with transaction.atomic():
        # Locking the report row serialises reorder work for every severity
        # group in that report, including callers that only normalise one group.
        report_model.objects.select_for_update().get(id=report_id)

        findings = list(
            model.objects.select_for_update()
            .filter(Q(report_id=report_id) & Q(severity_id=severity_id))
            .order_by("position", "id")
        )
        if not findings:
            return

        if moving_instance_id is not None:
            moving_finding = next(
                (finding for finding in findings if finding.id == moving_instance_id),
                None,
            )
            if moving_finding is not None:
                ordered_findings = [
                    finding for finding in findings if finding.id != moving_instance_id
                ]
                insert_at = _clamp_position(target_position, len(findings)) - 1
                ordered_findings.insert(insert_at, moving_finding)
                findings = ordered_findings

        for position, finding in enumerate(findings, start=1):
            if finding.position != position:
                model.objects.filter(id=finding.id).update(position=position)


def set_finding_positions(
    instance: django.db.models.Model, old_pos: [int, None], old_sev: [int, None], new_pos: int, new_sev: int
) -> None:
    """
    Updates the ``position`` value for a finding in a report. This is used when a finding is moved to a new position or
    changes severity.

    Reorder processing is serialised on the parent report row. The position
    updates use ``update()`` and are only issued when a row's position must
    change, so Hasura events generated by normalisation converge to no-ops.

    **Parameters**

    ``instance``
        Instance of :model:`reporting.ReportFindingLink`
    ``old_pos``
        The previous position assigned to the finding
    ``old_sev``
        The previous severity ID assigned to the finding
    ``new_pos``
        The new position assigned to the finding
    ``new_sev``
        The new severity ID assigned to the finding
    """
    # We don't import the model at the top of the file because it causes a circular import
    model = instance._meta.model
    report_model = instance.report._meta.model
    report_id = instance.report_id

    with transaction.atomic():
        # Serialise all reorder work for a report so concurrent Hasura events
        # cannot interleave read/renumber/write cycles for the same findings.
        report_model.objects.select_for_update().get(id=report_id)

        if old_pos and old_sev:
            if old_pos == new_pos and old_sev == new_sev:
                return None

            # Concurrent Hasura events can arrive after a newer reorder has
            # already moved this finding. Treat those stale events as clean-up
            # passes instead of replaying an old requested position.
            if instance.position != new_pos or instance.severity_id != new_sev:
                severity_ids = {old_sev, new_sev, instance.severity_id}
                for severity_id in severity_ids:
                    normalize_finding_positions(model, report_id, severity_id)
                return None

            if old_sev != new_sev:
                normalize_finding_positions(model, report_id, old_sev)
                normalize_finding_positions(
                    model,
                    report_id,
                    new_sev,
                    moving_instance_id=instance.id,
                    target_position=new_pos,
                )
            else:
                normalize_finding_positions(
                    model,
                    report_id,
                    new_sev,
                    moving_instance_id=instance.id,
                    target_position=new_pos,
                )
        else:
            # Insert events append new findings to the end of the severity group.
            group_count = model.objects.filter(
                Q(report_id=report_id) & Q(severity_id=new_sev)
            ).count()
            normalize_finding_positions(
                model,
                report_id,
                new_sev,
                moving_instance_id=instance.id,
                target_position=group_count,
            )
    return None
