# Generated by Django 2.2.3 on 2019-08-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_report_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfindinglink',
            name='finding_guidance',
            field=models.TextField(blank=True, help_text='Provide notes for your team that describes how the finding is intended to be used and any details that should be provided during editing', null=True, verbose_name='Finding Guidance'),
        ),
    ]
