# Generated by Django 2.2.3 on 2019-11-22 23:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_reportfindinglink_finding_guidance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide a description for this finding that introduces it', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='host_detection_techniques',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe how this finding can be detected on an endpoint - leave blank if this does not apply', null=True, verbose_name='Host Detection Techniques'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='impact',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe the impact of this finding on the affected entities', null=True, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='mitigation',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe how this finding can be resolved or addressed', null=True, verbose_name='Mitigation'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='network_detection_techniques',
            field=tinymce.models.HTMLField(blank=True, help_text='Describe how this finding can be detected on a network - leave blank if this does not apply', null=True, verbose_name='Network Detection Techniques'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='references',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide solid references for this finding, such as links to reference materials, tooling, and white papers', null=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='replication_steps',
            field=tinymce.models.HTMLField(blank=True, help_text='Provide an explanation for how the reader may reproduce this finding', null=True, verbose_name='Replication Steps'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(help_text='Select the project tied to this report', null=True, on_delete=django.db.models.deletion.CASCADE, to='rolodex.Project'),
        ),
    ]
