# Generated by Django 2.2.3 on 2020-09-18 23:23

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0006_auto_20200825_1947"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reporting", "0009_auto_20200915_0011"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/templates", location="/app/ghostwriter/reporting/templates/reports"
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provide a name to be used when selecting this template",
                        max_length=255,
                        null=True,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "upload_date",
                    models.DateField(
                        auto_now=True,
                        help_text="Date and time the template was first uploaded",
                        verbose_name="Upload Date",
                    ),
                ),
                (
                    "last_update",
                    models.DateField(
                        auto_now=True,
                        help_text="Date and time the report was last modified",
                        verbose_name="Last Modified",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Provide a description of this template", verbose_name="Description"
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False, help_text="Only administrators can edit this template", verbose_name="Protected"
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=False,
                        help_text="Make this the default template for all new reports or just for the selected client",
                        verbose_name="Default",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template will only be displayed for this client",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rolodex.Client",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["name", "document", "client"],
            },
        ),
    ]
