# Generated by Django 2.2.3 on 2020-09-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_reporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(help_text='Select the report template to use for ths report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.ReportTemplate'),
        ),
    ]
