# Generated by Django 3.0.10 on 2020-10-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0014_auto_20200924_1822"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "doc_type",
                    models.CharField(
                        help_text="Enter a file extension for a report template filetype",
                        max_length=5,
                        unique=True,
                        verbose_name="Document Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document type",
                "verbose_name_plural": "Document types",
                "ordering": ["doc_type"],
            },
        ),
        migrations.AlterModelOptions(
            name="reporttemplate",
            options={
                "ordering": ["-default", "doc_type", "client", "name"],
                "verbose_name": "Report template",
                "verbose_name_plural": "Report templates",
            },
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="changelog",
            field=models.TextField(
                blank=True,
                help_text="Add a line explaining any file changes",
                null=True,
                verbose_name="Template Change Log",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="doc_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the filetype for this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reporting.DocType",
            ),
        ),
    ]
