# Generated by Django 3.0.10 on 2020-10-17 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0015_auto_20201016_1756"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="template",
        ),
        migrations.AddField(
            model_name="report",
            name="docx_template",
            field=models.ForeignKey(
                help_text="Select the Word template to use for this report",
                limit_choices_to={"doc_type__iexact": "docx"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reporttemplate_docx_set",
                to="reporting.ReportTemplate",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="pptx_template",
            field=models.ForeignKey(
                help_text="Select the PowerPoint template to use for this report",
                limit_choices_to={"doc_type__iexact": "pptx"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reporttemplate_pptx_set",
                to="reporting.ReportTemplate",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="finding_guidance",
            field=models.TextField(
                blank=True,
                help_text="Provide notes for your team that describes how the finding is intended to be used or edited during editing",
                null=True,
                verbose_name="Finding Guidance",
            ),
        ),
    ]
