# Generated by Django 3.0.10 on 2020-10-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0016_auto_20201017_0014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="docx_template",
            field=models.ForeignKey(
                help_text="Select the Word template to use for this report",
                limit_choices_to={"doc_type__doc_type__iexact": "docx"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reporttemplate_docx_set",
                to="reporting.ReportTemplate",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="pptx_template",
            field=models.ForeignKey(
                help_text="Select the PowerPoint template to use for this report",
                limit_choices_to={"doc_type__doc_type__iexact": "pptx"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reporttemplate_pptx_set",
                to="reporting.ReportTemplate",
            ),
        ),
    ]
