# Generated by Django 3.0.10 on 2020-11-05 06:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0018_auto_20201027_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporttemplate",
            name="document",
            field=models.FileField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/templates", location="/app/ghostwriter/media/templates"
                ),
                upload_to="",
            ),
        ),
    ]
