# Generated by Django 3.2.11 on 2022-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0026_convert_linting_status_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cvss_score',
            field=models.CharField(blank=True, help_text='Set the CVSS score for this finding', max_length=4, verbose_name='CVSS Score v3.0'),
        ),
        migrations.AddField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Select the CVSS vector for this finding', max_length=54, verbose_name='CVSS Vector v3.0'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='cvss_score',
            field=models.CharField(blank=True, help_text='Set the CVSS score for this finding', max_length=4, verbose_name='CVSS Score v3.0'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Select the CVSS vector for this finding', max_length=54, verbose_name='CVSS Vector v3.0'),
        ),
    ]
