# Generated by Django 3.2.11 on 2022-11-16 22:19

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("reporting", "0031_alter_severity_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
