# Generated by Django 3.2.11 on 2022-12-14 21:32

import django.core.validators
from django.db import migrations, models

import ghostwriter.reporting.models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0034_reporttemplate_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportfindinglink",
            name="position",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Report Position"
            ),
        ),
        migrations.AlterField(
            model_name="severity",
            name="weight",
            field=models.IntegerField(
                default=ghostwriter.reporting.models.Severity.get_default_weight,
                help_text="Weight for sorting severity categories in reports (lower numbers are more severe)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Severity Weight",
            ),
        ),
    ]
