# Generated by Django 3.2.16 on 2023-01-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0035_auto_20221214_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='landscape',
            field=models.BooleanField(default=False, help_text='Flag this document as landscape orientation', verbose_name='Landscape Orientation'),
        ),
    ]
