# Generated by Django 3.2.16 on 2023-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_reporttemplate_landscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='p_style',
            field=models.CharField(blank=True, default=None, help_text='Provide the name of the style of new paragraphs. The style must be present in the template. Leave empty to use default Normal style.', max_length=255, null=True, verbose_name='Style of new paragraphs (leave empty for default - Normal)'),
        ),
    ]
