# Generated by Django 3.2.19 on 2023-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_reporttemplate_landscape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Set the CVSS vector for this finding', max_length=54, null=True, verbose_name='CVSS Vector v3.0'),
        ),
    ]
