# Generated by Django 3.2.19 on 2023-09-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0037_alter_reportfindinglink_cvss_vector"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE reporting_reportfindinglink ALTER COLUMN added_as_blank SET DEFAULT FALSE;",
        ),
    ]
