# Generated by Django 3.2.19 on 2023-09-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0037_reporttemplate_p_style'),
        ('reporting', '0038_alter_reportfindinglink_added_as_blank'),
    ]

    operations = [
    ]
