# Generated by Django 3.2.19 on 2023-09-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0040_alter_reporttemplate_p_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfindinglink',
            name='finding_type',
            field=models.ForeignKey(default=1, help_text='Select a finding category that fits', on_delete=django.db.models.deletion.PROTECT, to='reporting.findingtype'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='severity',
            field=models.ForeignKey(default=1, help_text='Select a severity rating for this finding that reflects its role in a system compromise', on_delete=django.db.models.deletion.PROTECT, to='reporting.severity'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='p_style',
            field=models.CharField(blank=True, default=None, help_text='Provide the name of a style in your template to use for new paragraphs (Word only).', max_length=255, null=True, verbose_name='New Paragraph Style'),
        ),
    ]
