# Generated by Django 3.2.19 on 2023-09-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0041_auto_20230919_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Set the CVSS vector for this finding', max_length=54, null=True, verbose_name='CVSS Vector v3.0'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='finding_type',
            field=models.ForeignKey(default=1, help_text='Select a finding category that fits', on_delete=django.db.models.deletion.PROTECT, to='reporting.findingtype'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.ForeignKey(default=1, help_text='Select a severity rating for this finding that reflects its role in a system compromise', on_delete=django.db.models.deletion.PROTECT, to='reporting.severity'),
        ),
    ]
