# Generated by Django 3.2.19 on 2023-11-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0042_auto_20230919_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['finding', 'report', 'document'], 'verbose_name': 'Evidence', 'verbose_name_plural': 'Evidence'},
        ),
        migrations.AddField(
            model_name='evidence',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.report'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.reportfindinglink'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('finding__isnull', True), ('report__isnull', False)), models.Q(('finding__isnull', False), ('report__isnull', True)), _connector='OR'), name='reporting_evidence_finding_or_report'),
        ),
    ]
