# Generated by Django 3.2.19 on 2024-02-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0042_auto_20230919_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvss_score',
            field=models.FloatField(blank=True, help_text='Set the CVSS score for this finding', null=True, verbose_name='CVSS Score'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Set the CVSS vector for this finding', max_length=54, null=True, verbose_name='CVSS Vector'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_score',
            field=models.FloatField(blank=True, help_text='Set the CVSS score for this finding', null=True, verbose_name='CVSS Score'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Set the CVSS vector for this finding', max_length=54, null=True, verbose_name='CVSS Vector'),
        ),
    ]
