# Generated by Django 3.2.19 on 2023-09-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0042_auto_20230919_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Set the CVSS vector for this finding', max_length=120, null=True, verbose_name='CVSS Vector v3.0'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Set the CVSS vector for this finding', max_length=120, null=True, verbose_name='CVSS Vector v3.0'),
        ),
    ]
