# Generated by Django 3.2.19 on 2023-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0042_auto_20230919_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
