# Generated by Django 3.2.19 on 2023-11-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0043_finding_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfindinglink',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
