# Generated by Django 3.2.19 on 2023-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0044_reportfindinglink_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
