# Generated by Django 3.2.19 on 2023-11-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0043_auto_20231116_1810'),
        ('reporting', '0044_reportobservationlink'),
        ('reporting', '0045_report_extra_fields'),
    ]

    operations = [
    ]
