# Generated by Django 3.2.19 on 2023-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0046_merge_20231130_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reportobservationlink',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
