# Generated by Django 3.2.19 on 2024-03-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0047_auto_20231201_1441"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE reporting_evidence ALTER COLUMN upload_date SET DEFAULT CURRENT_TIMESTAMP;",
        ),
        migrations.RunSQL(
            "ALTER TABLE reporting_reporttemplate ALTER COLUMN upload_date SET DEFAULT CURRENT_TIMESTAMP;",
        ),
    ]
