# Generated by Django 3.2.19 on 2024-03-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0048_auto_20240307_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='doc_type',
            field=models.CharField(help_text='Enter a file extension for a report template filetype', max_length=20, unique=True, verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='doctype',
            name='extension',
            field=models.CharField(default='', max_length=10, verbose_name='Document Extension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctype',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='doc_type',
            field=models.ForeignKey(blank=True, help_text='Select the file type and target for this template', null=True, on_delete=models.deletion.SET_NULL, to='reporting.doctype'),
        ),
    ]
