# Generated by Django 3.2.19 on 2024-04-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0049_extra_fields_db_default'),
        ('reporting', '0050_reporttemplate_filename_override'),
    ]

    operations = [
    ]
