# Generated by Django 3.2.19 on 2024-05-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0051_merge_20240429_1901'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE', reverse_sql='SET CONSTRAINTS ALL DEFERRED'),
        migrations.AlterField(
            model_name='evidence',
            name='friendly_name',
            field=models.CharField(help_text='Provide a simple name to be used to reference this evidence', max_length=255, verbose_name='Friendly Name'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS vector for this finding', max_length=54, verbose_name='CVSS Vector v3.0'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Provide a description for this finding that introduces it', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='finding_guidance',
            field=models.TextField(blank=True, default='', help_text='Provide notes for your team that describes how the finding is intended to be used or edited during editing', verbose_name='Finding Guidance'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='host_detection_techniques',
            field=models.TextField(blank=True, default='', help_text='Describe how this finding can be detected on an endpoint - leave blank if this does not apply', verbose_name='Host Detection Techniques'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='impact',
            field=models.TextField(blank=True, default='', help_text='Describe the impact of this finding on the affected entities', verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='mitigation',
            field=models.TextField(blank=True, default='', help_text='Describe how this finding can be resolved or addressed', verbose_name='Mitigation'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='network_detection_techniques',
            field=models.TextField(blank=True, default='', help_text='Describe how this finding can be detected on a network - leave blank if this does not apply', verbose_name='Network Detection Techniques'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='references',
            field=models.TextField(blank=True, default='', help_text='Provide solid references for this finding, such as links to tools and white papers', verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='replication_steps',
            field=models.TextField(blank=True, default='', help_text='Provide an explanation for how the reader may reproduce this finding', verbose_name='Replication Steps'),
        ),
        migrations.AlterField(
            model_name='findingnote',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Provide additional information about the finding', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='localfindingnote',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Provide additional information about the finding', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Provide a description for this observation that introduces it', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='affected_entities',
            field=models.TextField(blank=True, default='', help_text='Provide a list of the affected entities (e.g. domains, hostnames, IP addresses)', verbose_name='Affected Entities'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS vector for this finding', max_length=54, verbose_name='CVSS Vector v3.0'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Provide a description for this finding that introduces it', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='finding_guidance',
            field=models.TextField(blank=True, default='', help_text='Provide notes for your team that describes this finding within this report', verbose_name='Finding Guidance'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='host_detection_techniques',
            field=models.TextField(blank=True, default='', help_text='Describe how this finding can be detected on an endpoint - leave blank if this does not apply', verbose_name='Host Detection Techniques'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='impact',
            field=models.TextField(blank=True, default='', help_text='Describe the impact of this finding on the affected entities', verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='mitigation',
            field=models.TextField(blank=True, default='', help_text='Describe how this finding can be resolved or addressed', verbose_name='Mitigation'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='network_detection_techniques',
            field=models.TextField(blank=True, default='', help_text='Describe how this finding can be detected on a network - leave blank if this does not apply', verbose_name='Network Detection Techniques'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='references',
            field=models.TextField(blank=True, default='', help_text='Provide solid references for this finding, such as links to reference materials, tooling, and white papers', verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='replication_steps',
            field=models.TextField(blank=True, default='', help_text='Provide an explanation for how the reader may reproduce this finding', verbose_name='Replication Steps'),
        ),
        migrations.AlterField(
            model_name='reportobservationlink',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Provide a description for this observation that introduces it', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='changelog',
            field=models.TextField(blank=True, default='', help_text='Add a line explaining any file changes', verbose_name='Template Change Log'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(help_text='Provide a name to be used when selecting this template', max_length=255, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='p_style',
            field=models.CharField(blank=True, default='', help_text='Provide the name of a style in your template to use for new paragraphs (Word only).', max_length=255, verbose_name='New Paragraph Style'),
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED', reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
