# Generated by Django 3.2.19 on 2024-06-13 20:53

from django.db import migrations, models
import ghostwriter.reporting.models
import ghostwriter.reporting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0052_auto_20240516_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='document',
            field=models.FileField(blank=True, max_length=255, upload_to=ghostwriter.reporting.models.set_evidence_upload_destination, validators=[ghostwriter.reporting.validators.validate_evidence_extension]),
        ),
    ]
