# Generated by Django 3.2.19 on 2024-08-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0054_set_text_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cvss_v4_score',
            field=models.FloatField(blank=True, help_text='Set the CVSS v4.0 score for this finding', null=True, verbose_name='CVSS v4.0 Score'),
        ),
        migrations.AddField(
            model_name='finding',
            name='cvss_v4_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS v4.0 vector for this finding', max_length=255, verbose_name='CVSS v4.0 Vector'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='cvss_v4_score',
            field=models.FloatField(blank=True, help_text='Set the CVSS v4.0 score for this finding', null=True, verbose_name='CVSS v4.0 Score'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='cvss_v4_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS v4.0 vector for this finding', max_length=255, verbose_name='CVSS v4.0 Vector'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cvss_score',
            field=models.FloatField(blank=True, help_text='Set the CVSS score for this finding', null=True, verbose_name='CVSS v3.0 Score'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS vector for this finding', max_length=54, verbose_name='CVSS v3.0 Vector'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_score',
            field=models.FloatField(blank=True, help_text='Set the CVSS v3.0 score for this finding', null=True, verbose_name='CVSS v3.0 Score'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS v3.0 vector for this finding', max_length=54, verbose_name='CVSS v3.0 Vector'),
        ),
        migrations.AlterModelOptions(
            name="finding",
            options={
                "ordering": [
                    "severity",
                    models.OrderBy(
                        models.functions.comparison.Coalesce(
                            "cvss_v4_score", "cvss_score"
                        ),
                        descending=True,
                        nulls_last=True,
                    ),
                    "finding_type",
                    "title",
                ],
                "verbose_name": "Finding",
                "verbose_name_plural": "Findings",
            },
        ),
    ]
