# Generated by Django 3.2.19 on 2024-09-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0054_set_text_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvss_score',
            field=models.FloatField(blank=True, help_text='Set the CVSS score for this finding', null=True, verbose_name='CVSS Score'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS vector for this finding', max_length=255, verbose_name='CVSS Vector'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_score',
            field=models.FloatField(blank=True, help_text='Set the CVSS score for this finding', null=True, verbose_name='CVSS Score'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS vector for this finding', max_length=255, verbose_name='CVSS Vector'),
        ),
    ]
