# Generated by Django 3.2.19 on 2024-08-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0043_auto_20240204_1656'),
        ('reporting', '0054_set_text_defaults'),
    ]

    operations = [
    ]
