# Generated by Django 3.2.19 on 2025-03-06 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0055_auto_20240924_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='evidence_image_width',
            field=models.FloatField(blank=True, default=6.5, help_text='The width of inserted evidence images, in inches (Word only)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Evidence Image Width'),
        ),
    ]
