# Generated by Django 4.2 on 2025-02-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0055_auto_20240924_2108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="title",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Enter a title for this finding that will appear in reports",
                verbose_name="Title",
            ),
        ),
    ]
