# Generated by Django 3.2.19 on 2024-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0055_merge_0043_auto_20240204_1656_0054_set_text_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS vector for this finding', max_length=54, verbose_name='CVSS Vector'),
        ),
        migrations.AlterField(
            model_name='reportfindinglink',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', help_text='Set the CVSS vector for this finding', max_length=54, verbose_name='CVSS Vector'),
        ),
    ]
