# Generated by Django 3.2.19 on 2025-04-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0056_reporttemplate_evidence_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='upload_date',
            field=models.DateField(help_text='Date and time the template was first uploaded', verbose_name='Upload Date'),
        ),
    ]
