# Generated by Django 4.2 on 2025-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0056_alter_observation_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="Enter a title for this finding that will appear in reports",
                verbose_name="Title",
            ),
        ),
    ]
