# Generated by Django 4.2 on 2025-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0057_alter_finding_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportfindinglink",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="Enter a title for this finding that will appear in the reports",
                verbose_name="Title",
            ),
        ),
    ]
