# Generated by Django 4.2 on 2025-04-09 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0057_alter_reporttemplate_upload_date"),
        ("reporting", "0058_alter_reportfindinglink_title"),
    ]

    operations = []
