# Generated by Django 4.2 on 2025-10-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0059_merge_20250409_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="bloodhound_heading_offset",
            field=models.SmallIntegerField(
                default=0,
                blank=True,
                help_text="Headings in BloodHound finding descriptions will have their level offset by this amount",
                verbose_name="BloodHound Heading Offset",
            ),
        ),
    ]
