# Generated by Django 4.2.16 on 2025-11-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0060_reporttemplate_bloodhound_heading_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="include_bloodhound_data",
            field=models.BooleanField(
                default=False,
                help_text="Include data from BloodHound in the report context",
            ),
        ),
    ]
