# Generated by Django 4.2.16 on 2025-11-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0061_report_include_bloodhound_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="contains_bloodhound_data",
            field=models.BooleanField(
                default=False,
                help_text="Set to true if this template is designed to include data from BloodHound",
                verbose_name="Contains BloodHound Data",
            ),
        ),
    ]
