# Generated by Django 4.2.16 on 2026-01-27 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reporting", "0062_reporttemplate_contains_bloodhound_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acronym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acronym",
                    models.CharField(
                        help_text="The acronym text (e.g., CIA, FBI)",
                        max_length=50,
                        verbose_name="Acronym",
                    ),
                ),
                (
                    "expansion",
                    models.CharField(
                        help_text="The full text expansion of the acronym",
                        max_length=500,
                        verbose_name="Expansion",
                    ),
                ),
                (
                    "override_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this custom acronym should override a built-in one",
                        verbose_name="Override Built-in",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority for disambiguation when multiple expansions exist (higher = preferred)",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this acronym is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this acronym was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this acronym was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this acronym (null for system-imported acronyms)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Acronym",
                "verbose_name_plural": "Acronyms",
                "ordering": ["acronym", "-priority"],
            },
        ),
    ]
