# Generated by Django 4.2.16 on 2025-12-18 15:04

from django.db import migrations, models
import django.db.models.deletion

def finding_to_report(apps, schema_editor):
    Evidence = apps.get_model("reporting", "Evidence")
    db_alias = schema_editor.connection.alias

    # Can't join the referenced finding in an update statement, so have to update fields manually
    evidences = list(
        Evidence.objects.using(db_alias)
            .filter(finding__isnull=False, report__isnull=True)
            .select_related("finding")
            .only("report_id", "finding__report_id")
    )
    for evi in evidences:
        evi.report_id = evi.finding.report_id
    Evidence.objects.using(db_alias).bulk_update(evidences, ["report_id"], batch_size=512)

class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0062_reporttemplate_contains_bloodhound_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evidence",
            options={
                "ordering": ["report", "document"],
                "verbose_name": "Evidence",
                "verbose_name_plural": "Evidence",
            },
        ),
        migrations.RemoveConstraint(
            model_name="evidence",
            name="reporting_evidence_finding_or_report",
        ),
        migrations.RunPython(finding_to_report),
        migrations.AlterField(
            model_name="evidence",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reporting.report"
            ),
        ),
        migrations.RemoveField(
            model_name="evidence",
            name="finding",
        ),
    ]
