# Generated by Django 4.2.16 on 2026-02-24 00:00

# Django Imports
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0062_reporttemplate_contains_bloodhound_data"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE reporting_report ALTER COLUMN include_bloodhound_data SET DEFAULT true;",
        ),
        migrations.RunSQL(
            "ALTER TABLE reporting_report ALTER COLUMN last_update SET DEFAULT CURRENT_DATE;",
        ),
        migrations.RunSQL(
            "ALTER TABLE reporting_reporttemplate ALTER COLUMN last_update SET DEFAULT CURRENT_DATE;",
        ),
        migrations.AlterField(
            model_name="report",
            name="project",
            field=models.ForeignKey(
                default=1,
                help_text="Select the project tied to this report",
                on_delete=django.db.models.deletion.CASCADE,
                to="rolodex.project",
            ),
            preserve_default=False,
        ),
    ]
