# Generated by Django 4.2.16 on 2026-02-24 00:00

# Django Imports
import django.db.models.deletion
from django.db import migrations, models


def check_reports_without_project(apps, schema_editor):
    """
    Block the migration if any Report rows have a NULL project_id.

    The Ghostwriter UI has always required a project when creating a report,
    so NULL values can only exist from direct GraphQL mutations that bypassed
    form validation. There is no safe automatic resolution — an operator must
    assign each orphaned report to a valid project (or delete it) before this
    migration can proceed.
    """
    Report = apps.get_model("reporting", "Report")
    orphan_ids = list(Report.objects.filter(project__isnull=True).values_list("id", flat=True))
    if orphan_ids:
        raise Exception(
            f"Migration blocked: {len(orphan_ids)} report(s) have no project assigned "
            f"(IDs: {orphan_ids}). These were likely created via the GraphQL API. "
            "Please assign each report to a valid project (or delete it) before running "
            "this migration."
        )


class Migration(migrations.Migration):
    dependencies = [
        # Required because AlterField references rolodex.Project
        ("rolodex", "0059_merge_20251027_1706"),
        ("reporting", "0062_reporttemplate_contains_bloodhound_data"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE reporting_report ALTER COLUMN include_bloodhound_data SET DEFAULT true;",
        ),
        migrations.RunSQL(
            "ALTER TABLE reporting_report ALTER COLUMN last_update SET DEFAULT CURRENT_DATE;",
        ),
        migrations.RunSQL(
            "ALTER TABLE reporting_reporttemplate ALTER COLUMN last_update SET DEFAULT CURRENT_DATE;",
        ),

        # Check for any orphaned reports before enforcing the NOT NULL constraint
        migrations.RunPython(check_reports_without_project, migrations.RunPython.noop),

        # Make project non-nullable — no arbitrary default needed since NULLs are now gone
        migrations.AlterField(
            model_name="report",
            name="project",
            field=models.ForeignKey(
                help_text="Select the project tied to this report",
                on_delete=django.db.models.deletion.CASCADE,
                to="rolodex.project",
            ),
        ),
    ]
