# Generated by Django 4.2.16 on 2026-01-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0063_acronym"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="acronym",
            index=models.Index(
                fields=["acronym", "is_active"], name="reporting_a_acronym_f840a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acronym",
            index=models.Index(
                fields=["acronym", "-priority"], name="reporting_a_acronym_f768d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acronym",
            index=models.Index(
                fields=["override_builtin", "is_active"],
                name="reporting_a_overrid_ae82b7_idx",
            ),
        ),
    ]
