# Generated by Django 4.2.16 on 2026-02-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rolodex", "0059_merge_20251027_1706"),
        ("reporting", "0063_set_report_field_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="project",
            field=models.ForeignKey(
                default=5,
                help_text="Select the project tied to this report",
                on_delete=django.db.models.deletion.CASCADE,
                to="rolodex.project",
            ),
            preserve_default=False,
        ),
    ]
