# Generated by Django 4.2.16 on 2026-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0064_alter_report_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportobservationlink",
            name="complete",
            field=models.BooleanField(
                default=False,
                help_text="Mark the observation as ready for a QA review",
                verbose_name="Completed",
            ),
        ),
    ]
