# Generated by Django 4.2.16 on 2026-01-28 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0064_acronym_reporting_a_acronym_f840a2_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acronym",
            options={
                "ordering": ["acronym", "-priority"],
                "verbose_name": "Acronym",
                "verbose_name_plural": "Acronyms",
            },
        ),
        migrations.RemoveField(
            model_name="acronym",
            name="category",
        ),
    ]
