# Generated by Django 4.2.16 on 2026-04-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0065_reportobservationlink_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="evidence_image_alignment",
            field=models.CharField(
                choices=[
                    ("USE_GLOBAL", "Use global default"),
                    ("LEFT", "Left"),
                    ("CENTER", "Center"),
                    ("RIGHT", "Right"),
                ],
                default="USE_GLOBAL",
                help_text="Override the global image evidence alignment for this template (Word only).",
                max_length=16,
                verbose_name="Image Evidence Alignment",
            ),
        ),
    ]
