# Generated by Django

import os
from django.db import migrations


def load_default_acronyms(apps, schema_editor):
    """Load bundled acronyms from YAML file into database."""
    import sys
    
    # Skip loading during tests
    if 'test' in sys.argv:
        return
    
    Acronym = apps.get_model('reporting', 'Acronym')
    
    # Skip if acronyms already exist (don't overwrite user data)
    if Acronym.objects.exists():
        return
    
    # Read bundled YAML file
    yaml_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
        'javascript', 'src', 'data', 'acronyms.yml'
    )
    
    if not os.path.exists(yaml_path):
        print(f"Warning: Bundled acronyms file not found at {yaml_path}")
        return
    
    try:
        import yaml
        
        with open(yaml_path, 'r') as f:
            data = yaml.safe_load(f)
        
        if not isinstance(data, dict):
            print("Warning: Invalid YAML structure in bundled acronyms")
            return
        
        created_count = 0
        for acronym_text, expansions in data.items():
            if not isinstance(expansions, list):
                continue
            
            # Process each expansion with priority based on order
            for index, expansion_data in enumerate(expansions):
                if not isinstance(expansion_data, dict):
                    continue
                
                if 'full' not in expansion_data:
                    continue
                
                expansion_text = expansion_data['full']
                
                # Higher priority for earlier entries (reverse index)
                priority = len(expansions) - index
                
                # Create acronym
                Acronym.objects.create(
                    acronym=acronym_text,
                    expansion=expansion_text,
                    priority=priority,
                    created_by=None,  # System-imported
                    is_active=True,
                )
                created_count += 1
        
        print(f"Loaded {created_count} default acronym(s) from bundled YAML")
    
    except Exception as e:
        print(f"Warning: Failed to load default acronyms: {e}")


def reverse_load_default_acronyms(apps, schema_editor):
    """Remove default acronyms (those with created_by=None)."""
    Acronym = apps.get_model('reporting', 'Acronym')
    deleted_count = Acronym.objects.filter(created_by__isnull=True).delete()[0]
    if deleted_count > 0:
        print(f"Removed {deleted_count} default acronym(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0065_alter_acronym_options_remove_acronym_category'),
    ]

    operations = [
        migrations.RunPython(load_default_acronyms, reverse_load_default_acronyms),
    ]
