# Generated by Django 4.2.15 on 2025-06-01

from django.db import migrations, models


def populate_risk_rich_text(apps, schema_editor):
    mapping_model = apps.get_model("reporting", "RiskScoreRangeMapping")
    for record in mapping_model.objects.all():
        if record.risk_rich_text:
            continue
        record.risk_rich_text = record.risk
        record.save(update_fields=["risk_rich_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0065_adjust_cloud_scoping_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscorerangemapping",
            name="risk_rich_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rich Text version of the risk bucket label.",
                verbose_name="Risk label rich text",
            ),
        ),
        migrations.RunPython(populate_risk_rich_text, migrations.RunPython.noop),
    ]
