# Generated by Django 4.2.16 on 2025-12-17 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0062_reporttemplate_contains_bloodhound_data"),
        ("reporting", "0066_riskscorerangemapping_rich_text"),
    ]

    operations = []
