# Generated by Django 5.2.14 on 2026-08-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0071_protect_global_report_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporttemplate",
            name="changelog",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Track and explain any file changes",
                verbose_name="Template Change Log",
            ),
        ),
    ]
