#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

AVATAR_DIR=/app/ghostwriter/media/user_avatars
EVIDENCE_DIR=/app/ghostwriter/media/evidence

[[ ! -d "$EVIDENCE_DIR" ]] && mkdir -p "$EVIDENCE_DIR" && chown -R django "$EVIDENCE_DIR"
[[ ! -d "$AVATAR_DIR" ]] && mkdir -p "$AVATAR_DIR" && chown -R django "$AVATAR_DIR" 

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
