#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

AVATAR_DIR=/app/ghostwriter/media/images/user_avatars
EVIDENCE_DIR=/app/ghostwriter/media/evidence
TEMPLATE_DIR=/app/ghostwriter/media/templates
ARCHIVE_DIR=/app/ghostwriter/media/archives

TEMPLATE_PATH_DOCX=/app/ghostwriter/reporting/templates/reports/template.docx
TEMPLATE_PATH_PPTX=/app/ghostwriter/reporting/templates/reports/template.pptx

[[ ! -d "$EVIDENCE_DIR" ]] && mkdir -p "$EVIDENCE_DIR" && chown -R django "$EVIDENCE_DIR"
[[ ! -d "$AVATAR_DIR" ]] && mkdir -p "$AVATAR_DIR" && chown -R django "$AVATAR_DIR"
[[ ! -d "$TEMPLATE_DIR" ]] && mkdir -p "$TEMPLATE_DIR" && chown -R django "$TEMPLATE_DIR"
[[ ! -d "$ARCHIVE_DIR" ]] && mkdir -p "$ARCHIVE_DIR" && chown -R django "$ARCHIVE_DIR"

cp -u -p "$TEMPLATE_PATH_DOCX" "$TEMPLATE_DIR"
cp -u -p "$TEMPLATE_PATH_PPTX" "$TEMPLATE_DIR"

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
# /usr/local/bin/daphne -b 0.0.0.0 -p 8000 config.asgi:application
uvicorn config.asgi:application --host 0.0.0.0 --port 8000
