# Generated by Django 3.2.19 on 2023-06-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230615_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_finding_delete',
            field=models.BooleanField(default=False, help_text='Allow the user to delete findings in the library (only applies to accounts with the User role)', verbose_name='Allow Finding Deleting'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enable_finding_create',
            field=models.BooleanField(default=False, help_text='Allow the user to create new findings in the library (only applies to account with the User role)', verbose_name='Allow Finding Creation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enable_finding_edit',
            field=models.BooleanField(default=False, help_text='Allow the user to edit findings in the library (only applies to accounts with the User role)', verbose_name='Allow Finding Editing'),
        ),
    ]
