# Generated by Django 3.2.19 on 2023-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='require_2fa',
            field=models.BooleanField(default=False, help_text='Require the user to set up two-factor authentication', verbose_name='Require 2FA'),
        ),
    ]
