# Generated by Django 3.2.19 on 2024-02-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_require_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_observation_create',
            field=models.BooleanField(default=False, help_text='Allow the user to create new observations in the library (only applies to account with the User role)', verbose_name='Allow Observation Creation'),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_observation_delete',
            field=models.BooleanField(default=False, help_text='Allow the user to delete observations in the library (only applies to accounts with the User role)', verbose_name='Allow Observation Deleting'),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_observation_edit',
            field=models.BooleanField(default=False, help_text='Allow the user to edit observations in the library (only applies to accounts with the User role)', verbose_name='Allow Observation Editing'),
        ),
    ]
