# Generated by Django 4.2.16 on 2025-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_auto_20240220_1810"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="require_2fa",
        ),
        migrations.AddField(
            model_name="user",
            name="require_mfa",
            field=models.BooleanField(
                db_column="require_2fa",
                default=False,
                help_text="Require the user to set up multi-factor authentication",
                verbose_name="Require MFA",
            ),
        ),
    ]
