# Generated by Django 3.2.19 on 2024-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20240220_1810"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short professional biography shown on your profile and project teams",
                verbose_name="Bio",
            ),
        ),
    ]
