# Generated by Django 4.2.16 on 2026-07-28

# Django Imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_user_require_2fa_user_require_mfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sidebar_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Versioned IDs for the user's pinned sidebar shortcuts",
            ),
        ),
    ]
