# Generated by Django 4.2.16 on 2025-12-17 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_user_require_2fa_user_require_mfa"),
        ("users", "0013_user_bio"),
    ]

    operations = []
