# Generated by Django 5.2.8 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_user_sidebar_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="workspace_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Versioned pinned work and recent working-report IDs",
            ),
        ),
    ]
