# Generated by Django 3.2.19 on 2024-08-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_modify_client_permissions_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="enable_client_create",
            field=models.BooleanField(
                default=False,
                help_text="Allow the user to create new clients in the library and create projects for any client (only applies to account with the User role)",
                verbose_name="Allow Client and Project Creation",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="enable_client_delete",
            field=models.BooleanField(
                default=False,
                help_text="Allow the user to delete clients in the library and delete projects for any client (only applies to accounts with the User role)",
                verbose_name="Allow Client and Project Deletion",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="enable_client_edit",
            field=models.BooleanField(
                default=False,
                help_text="Allow the user to edit clients in the library and edit projects for any client (only applies to accounts with the User role)",
                verbose_name="Allow Client and Project Editing",
            ),
        ),
    ]
