# Generated by Django 5.2.14 on 2026-10-05 16:29

from django.db import migrations, models

HEALTH_TASK = "ghostwriter.status.tasks.refresh_dashboard_health"
HEALTH_SCHEDULE_NAME = "Dashboard system health"


def create_health_schedule(apps, schema_editor):
    """Install the monitor once, preserving any existing administrator settings."""
    schedule = apps.get_model("django_q", "Schedule")
    schedule.objects.using(schema_editor.connection.alias).get_or_create(
        func=HEALTH_TASK,
        name=HEALTH_SCHEDULE_NAME,
        defaults={"schedule_type": "I", "minutes": 1, "repeats": -1},
    )


def remove_health_schedule(apps, schema_editor):
    schedule = apps.get_model("django_q", "Schedule")
    schedule.objects.using(schema_editor.connection.alias).filter(
        func=HEALTH_TASK, name=HEALTH_SCHEDULE_NAME
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("status", "0001_drop_legacy_health_check_db_table"),
        ("django_q", "0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardHealthSnapshot",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("checked_at", models.DateTimeField()),
                ("summary", models.JSONField(default=dict)),
            ],
        ),
        migrations.RunPython(create_health_schedule, remove_health_schedule),
    ]
