name: Update Version on Release

on:
#  push:
#    tags:
#      - 'v*'
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - release/*

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Update version and date
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          RELEASE_DATE=$(date +"%d %B %Y")
          echo "TAG_NAME: $TAG_NAME"
          echo "RELEASE_DATE: $RELEASE_DATE"
          python scripts/update_version.py "$TAG_NAME" "$RELEASE_DATE"
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add config/settings/base.py VERSION
          git diff --cached --quiet || git commit -m "Update version to $TAG_NAME ($RELEASE_DATE)"
          git push
